In [1]:
from jupyter_dash import JupyterDash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Output, Input
import os 
import pandas as pd
import numpy as np
from plotly import graph_objects as go
import functools as ft 

In [23]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

In [2]:
pwd

'c:\\Users\\HP\\source\\repos\\STARS_dashboard\\stars-dashboard'

In [3]:
os.chdir(r"C:\Users\HP\source\repos\STARS_dashboard")
os.getcwd()

'C:\\Users\\HP\\source\\repos\\STARS_dashboard'

In [4]:
# setting global path
path_learnassess_year1 = "data/ipa-data/learning_assessment/data_entry/year1/clean"

In [2]:
# app instantiation
app = JupyterDash(__name__)

In [4]:
# app layout
app.layout = html.Div([
    dcc.Dropdown(
        options=[{"label" : color,
                 "value" : color }
                 for color in ["blue","green","yellow"]
    ]),
    html.Div()
])

In [ ]:
# run the app
if __name__ == "__main__":
    app.run_server(mode = "inline",port = "3333")

In [ ]:
#using callbacks

# app instantiation
app = JupyterDash(__name__)

# app layout
app.layout = html.Div([
    dcc.Dropdown(id= "color_dropdown",
                 options = [
                    {"label": color, 
                    "value": color}
                    for color in ["Blue","Black", "Green"]
                ]),
    html.Br(),
    html.Div(id="display_dropdown")
])

# callback functions
@app.callback(Output(component_id = "display_dropdown",
                     component_property= "children"),
              Input(component_id = "color_dropdown",
                    component_property = "value"))

def display_selected_color(color):
    if color is None:
        color = "Nothing"
    return "The color is " + color 

# run the app
if __name__ == "__main__":
    app.run_server(mode = "inline", port = 2)

In [ ]:
# app instantiation
app = JupyterDash(__name__)

# information on the activities
timeline = ["first year", "second year"]
short_description = {"first year":"The data collection activities spanned 10 districts while gathering data on 343 schools where 100 schools were in the\
                     control group while 243 schools were in the treatment group",
                     "second year":"489 schools were visited across 10 districts to conduct STARS data collection activities."}

# app layout
app.layout = html.Div([
    dcc.Dropdown(id = "id_dropdown",
                 options = [{"label" : time,
                            "value": time}
                            for time in timeline]),
    html.Br(),
    html.Div(id = "output_dropdown")
])

# callback functions
@app.callback(Output(component_id = "output_dropdown",
                     component_property= "children"),
              Input(component_id = "id_dropdown",
                    component_property = "value"))

def activity_info(timeline):
    if timeline is None:
        return "STARS project is being implemented by Innovation for Poverty Actions in partnership with Georgetown University, MINEDUC, REB, and NESA"
    return [html.H3(timeline), f'For the  {timeline}, {short_description[timeline]}']

# run the app
if __name__ == "__main__":
    app.run_server(mode = "inline", port = 5)

## Working with Plotly's Figure Objects

### Understanding the Figure Object

In [ ]:
go.Figure()

In [ ]:
fig = go.Figure()
fig.add_scatter(x=[1,2,3],y=[4,2,3])
fig.show()

In [ ]:
fig.add_scatter(x = [3,5,2,4], y = [5,2,6,0])

#### Layout Attribute

In [ ]:
fig.layout.title = "Example 0"
fig.layout.xaxis.title = "x axis"
fig.layout.yaxis.title = "y axis"
fig.show()

In [ ]:
# exploring figure objects
fig.show("json")

In [ ]:
fig.show()

In [ ]:
fig.show(config = {"displaylogo" : False,
                   "modeBarButtonsToAdd" : ["drawrect",
                                            "drawcircle",
                                            "eraseshape"]})

#### Converting figures

In [9]:
# To Html
fig.write_html("html_plot.html",
               config = {"toImageButtonOptions" : {"format" : "svg"}})

In [ ]:
# to images
fig.write_image("apps/images/example_image.svg",
                height = 800, width = 900)

# plotting using real data

In [4]:
# import datasets to use

# we start by using data entry data from year 1

data_entry_team_1 = pd.read_stata(r"data\ipa-data\learning_assessment\data_entry\year1\clean\first_entry\Final Assessment First Entry Clean.dta")
data_entry_team_2 = pd.read_stata(r"data\ipa-data\learning_assessment\data_entry\year1\clean\second_entry\Final Assessment Second Entry Clean.dta")
data_entry_reconciliation = pd.read_stata(r"data\ipa-data\learning_assessment\data_entry\year1\clean\reconciliation\reconciled_clean.dta")

In [ ]:
data_entry_team_1.head(5)

In [ ]:
data_entry_team_1.dropna(axis=1,how="all").describe(include = [np.number]).T

In [ ]:
data_entry_team_1.dropna(axis=1,how="all").describe(include="all",datetime_is_numeric=True).T

In [8]:
data_entry_team_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 56906 entries, 0 to 56905
Columns: 456 entries, deviceid to v454
dtypes: category(407), datetime64[ns](5), float64(10), object(34)
memory usage: 43.9+ MB


In [5]:
# check columns that are entirely empty
empty_cols = [col for col in data_entry_team_1 if  data_entry_team_1[col].isna().all()]
print(empty_cols)

['kin1marks_p6_kin1p6_kin_q021p6_k', 'kin1marks_p6_kin1p6_kin_q061p6_k', 'kin1marks_p6_kin1p6_kin_q101p6_k', 'v453', 'kin1marks_p5_kin1p5_kin_q141p5_k', 'v454']


In [6]:
#drop empty cols
df_team_1 = data_entry_team_1.copy()
df_team_1 = df_team_1.drop(empty_cols,axis = 1)

# check columns that are entirely empty
empty_cols0 = [col for col in df_team_1 if  df_team_1[col].isna().all()]
print(empty_cols0)

[]


In [7]:
# let's check categorical columns
#cat_cols = [col for col in df_team_1 if df_team_1[col].dtypes.name == "category"]
#print(cat_cols)

cat_cols0 = df_team_1.select_dtypes(["category"]).columns
print(cat_cols0)

Index(['spv', 'fo', 'eng_participation', 'p1_eng_q01_sub1', 'p1_eng_q01_sub2',
       'p1_eng_q02_sub1', 'p1_eng_q02_sub2', 'p1_eng_q02_sub3',
       'p1_eng_q03_sub1', 'p1_eng_q03_sub2',
       ...
       'p2_leg_q01_sub1', 'p2_leg_q02_sub1', 'p2_leg_q03_sub1',
       'p2_leg_q04_sub1', 'p2_leg_q05_sub1', 'p3_leg_q01_sub1',
       'p3_leg_q02_sub1', 'p3_leg_q03_sub1', 'p3_leg_q04_sub1',
       'p3_leg_q05_sub1'],
      dtype='object', length=407)


we have 407 columns that are categorical, this makes sense where, except for svp and fo, the columns represent participation or marks received by students with 3 choices: correct, incorrect, or left blank

In [ ]:
# let's visualize categorical columns
print(df_team_1[cat_cols0])

let's check for one of the categorical columns the choices available:

In [29]:
#print(df_team_1["p1_eng_q02_sub3"].cat.codes.unique())
#print(df_team_1["p1_eng_q02_sub3"].cat.categories.unique())
print(dict(enumerate(df_team_1["p1_eng_q02_sub3"].cat.categories)))
print(dict(enumerate(df_team_1["eng_participation"].cat.categories)))
print(dict(enumerate(df_team_1["spv"].cat.categories)))
print(dict(enumerate(df_team_1["fo"].cat.categories)))

{0: 'Left blank', 1: 'No', 2: 'Yes'}
{0: 'No', 1: 'Yes'}
{0: 'Shema Christian', 1: 'NAHIMANA Reverien   ', 2: 'Havugimana Saidi', 3: 'Uwimana  Pauline', 4: 'NTAREMBA George   ', 5: 'Hatangimana Gisele'}
{0: 'Rushambara Alexis', 1: 'NSHIMIYIMANA PASCAL', 2: 'Habonimana Gabriel', 3: 'Nirere Sandrine', 4: 'NIYIBIZI Leandre', 5: 'UWASE Francine\xa0', 6: 'Uwizeyimana Viateur', 7: 'Rusangwa Adolphe', 8: 'IRADUKUNDA GAHIRE ADOLPHE', 9: 'Ingabire Emelyne', 10: 'MUSHIMIRE Clarisse', 11: 'Mudahogora Placidie', 12: 'TUYISENGE ANICK', 13: 'Bagirishyaka Fulgence', 14: 'Fidele Iragena', 15: 'MUKANKOMEJE  Chantal', 16: 'NABAGIZE JUSTINE', 17: 'NTAWUSIGIRYAYO  Eric ', 18: 'IRAMBONA Valens', 19: 'Shingiro John', 20: 'UMUBYEYI MARIE GRACE', 21: 'MURAGIJIMANA Obadia', 22: 'MASENGESHO Samuel', 23: 'UMUBYEYI Claudine', 24: 'DUFATANYE Devota', 25: 'NSHIMIYIMANA Bernard', 26: 'MUKANSANGA Jacqueline', 27: 'UWIMANA Jeannette', 28: 'NAHAYO Jean Damascene', 29: 'DUSENGUMUREMYI Yvonne', 30: 'NSENGUMUREMYI Felix',

In [8]:
enumerators = dict(enumerate(df_team_1["fo"].cat.categories))
enumerators = pd.DataFrame(enumerators.items(),columns=["codes", "names"])
enumerators.head(20)

codes                      names
0       0          Rushambara Alexis
1       1        NSHIMIYIMANA PASCAL
2       2         Habonimana Gabriel
3       3            Nirere Sandrine
4       4           NIYIBIZI Leandre
5       5            UWASE Francine 
6       6        Uwizeyimana Viateur
7       7           Rusangwa Adolphe
8       8  IRADUKUNDA GAHIRE ADOLPHE
9       9           Ingabire Emelyne
10     10         MUSHIMIRE Clarisse
11     11        Mudahogora Placidie
12     12            TUYISENGE ANICK
13     13      Bagirishyaka Fulgence
14     14             Fidele Iragena
15     15       MUKANKOMEJE  Chantal
16     16           NABAGIZE JUSTINE
17     17      NTAWUSIGIRYAYO  Eric 
18     18            IRAMBONA Valens
19     19              Shingiro John

In [9]:
#we are going to convert categorical variables to their numeric values
df_team_1[cat_cols0] = df_team_1[cat_cols0].apply(lambda x: x.cat.codes)
#check the results
print(df_team_1.select_dtypes(["category"]).columns)
print(df_team_1["p1_eng_q02_sub3"].unique())
print(df_team_1["eng_participation"].unique())
print(df_team_1["spv"].unique())
print(df_team_1["fo"].unique())

Index([], dtype='object')
[-1  2  1  0]
[ 1  0 -1]
[0 1 4 2 5 3]
[110 109   2  89 103  99  36 112  13  98   5 137  40  48 119  26   8 140
 105  76  42  74  14  59  71 134  91 127  17   4  95  37 116 128  31  52
  61 121  51  96  77 102  54  55 122  97 113 139  21 136  35  62  90 108
  85 124  79  49  75 138  33  86  68  83 126  64  28  44  30  81   6  88
  23  41  11 107  67  65 120 100  15 123  34  10  43  47  57  94   9   3
  12  50  70  22  69 131 125 101  20  38  87  16  73  63  92   7 133  46
  45 104  80  78  84 114  32   0  72  66  53 117 130 118  24  93  18 106
  82  39  27  60 129 141  19  56  29  58 115   1 111 132  25 135]


In [37]:
df_team_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 56906 entries, 0 to 56905
Columns: 450 entries, deviceid to enddate
dtypes: datetime64[ns](5), float64(4), int16(1), int8(406), object(34)
memory usage: 41.2+ MB


we have successfully converted categorical variables to numeric variables

In [10]:
#check object type variables
object_cols = df_team_1.select_dtypes(["object"]).columns
print(object_cols)

Index(['deviceid', 'devicephonenum', 'username', 'device_info', 'duration',
       'caseid', 'district', 'sector', 'school', 'grade', 'student_code',
       'student_code_other', 'student_code_name', 'time_check_eng_1',
       'time_check_eng_2', 'time_check_eng_3', 'time_check_eng_4',
       'time_check_eng_5', 'time_check_eng_6', 'time_check_math_1',
       'time_check_math_2', 'time_check_math_3', 'time_check_math_4',
       'time_check_math_5', 'time_check_math_6', 'time_check_kiny_4',
       'time_check_kiny_5', 'time_check_kiny_6', 'time_check_kiny_1',
       'time_check_kiny_2', 'time_check_kiny_3', 'time_check_end',
       'instancename', 'key'],
      dtype='object')


In [ ]:
# let's view the object type variables
df_team_1[object_cols].head()

In [19]:
#drop unuseful columns
df_team_1 = df_team_1.drop(['deviceid', 'devicephonenum', 'username', 'caseid','device_info','instancename', 'key'], axis=1)

In [20]:
#check object type variables again
object_cols0 = df_team_1.select_dtypes(["object"]).columns
print(object_cols0)

Index(['duration', 'district', 'sector', 'school', 'grade', 'student_code',
       'student_code_other', 'student_code_name', 'time_check_eng_1',
       'time_check_eng_2', 'time_check_eng_3', 'time_check_eng_4',
       'time_check_eng_5', 'time_check_eng_6', 'time_check_math_1',
       'time_check_math_2', 'time_check_math_3', 'time_check_math_4',
       'time_check_math_5', 'time_check_math_6', 'time_check_kiny_4',
       'time_check_kiny_5', 'time_check_kiny_6', 'time_check_kiny_1',
       'time_check_kiny_2', 'time_check_kiny_3', 'time_check_end',
       'student_code_unsure'],
      dtype='object')


In [ ]:
print(df_team_1["school"].unique())

In [ ]:
print(df_team_1["student_code"].unique())
print(df_team_1["student_code_name"].unique())
print(df_team_1["student_code_other"].unique())
print(df_team_1["time_check_eng_1"].unique())
print(df_team_1["time_check_end"].unique())

In [ ]:
df_team_1[["student_code","student_code_other"]][df_team_1["student_code_other"]!="."]

In [53]:
df_team_1["student_code_other"][41] == df_team_1["student_code"][41] 

True

In [21]:
#Assigning values to student_code_other based on student_code variable
df_team_1.loc[df_team_1["student_code_other"] == df_team_1["student_code"], "student_code_other"] = "."
print(df_team_1.student_code_other.unique())

['.' '-555' '555' '540712210384' '21108002025' '555555555555'
 '510712002010' '540712210425' '421807055001' '4305061550' '5707122003003'
 '4211020003025' '211001230088' '421102210191' '42111204027'
 '320028002001']


In [ ]:
df_team_1.loc[df_team_1["student_code_other"] != ".", ["student_code","student_code_other"]]

In [17]:
df_team_1.loc[df_team_1["student_code_other"] != ".", "student_code_other"].unique()

array(['-555', '555', '540712210384', '21108002025', '555555555555',
       '510712002010', '540712210425', '421807055001', '4305061550',
       '5707122003003', '4211020003025', '211001230088', '421102210191',
       '42111204027', '320028002001'], dtype=object)

In [ ]:
df_team_1.loc[df_team_1["student_code_other"].isin(['540712210384', '21108002025',
       '510712002010', '540712210425', '421807055001', '4305061550',
       '5707122003003', '4211020003025', '211001230088', '421102210191',
       '42111204027', '320028002001']), ["student_code","student_code_other"]]

let's create a column that will help us track these inconsistencies

In [22]:
df_team_1["student_code_unsure"] = np.where(df_team_1["student_code_other"].isin(['540712210384', '21108002025',
       '510712002010', '540712210425', '421807055001', '4305061550',
       '5707122003003', '4211020003025', '211001230088', '421102210191',
       '42111204027', '320028002001']),"flagged","passed")


In [16]:
print(df_team_1["student_code_unsure"].value_counts())

passed     56894
flagged       12
Name: student_code_unsure, dtype: int64


In [16]:
# check if student_code column is unique and doesn't have duplicates
df_team_1["student_code"].is_unique

False

It seems like we have duplicates in the student code variable.
Let us count how many duplicates we have

In [17]:
# check how many dups we have
df_team_1["student_code"].duplicated().sum()

451

we have around 451 duplicates

In [ ]:
#let us view the duplicates
df_team_1[df_team_1["student_code"].isin(df_team_1["student_code"][df_team_1["student_code"].duplicated()])].sort_values(["student_code","submissiondate"])

In [23]:
df_team_1_unique = df_team_1.sort_values(["student_code","submissiondate"]).drop_duplicates("student_code",keep="last")
# check how many dups we have
print(df_team_1_unique["student_code"].duplicated().sum())

0


Now that we have treated student_code duplicates, we can move on with our feature cleaning activities

In [24]:
#changing column types to numeric, Datetime, and string

#numeric
df_team_1_unique[["duration","school","student_code"]] = df_team_1_unique[["duration","school","student_code"]].apply(pd.to_numeric)

In [25]:
#datetime
# select columns that starts with time_check
time_cols = [col for col in df_team_1_unique if col.startswith("time_check")]

df_team_1_unique[time_cols] = df_team_1_unique[time_cols].apply(pd.to_datetime)

In [ ]:
# Let us look at how the datetime transformation was executed
df_team_1_unique[time_cols]

In [24]:
# let's check how many object type columns are left
print(df_team_1_unique.select_dtypes("object").columns)

Index(['district', 'sector', 'grade', 'student_code_other',
       'student_code_name', 'student_code_unsure'],
      dtype='object')


In [26]:
# first we drop unwanted columns
unwanted_cols = ['student_code_other', 'student_code_name']
df_team_1_unique = df_team_1_unique.drop(unwanted_cols, axis=1)


In [27]:
# string
string_cols = ['district', 'sector', 'grade', 'student_code_unsure']

df_team_1_unique[string_cols] = df_team_1_unique[string_cols].apply(lambda col: col.map(repr)) #interesting
print(df_team_1_unique[string_cols].head())

         district        sector grade student_code_unsure
41776  'Kicukiro'     'Gikondo'  'P2'            'passed'
32697  'Kicukiro'     'Kanombe'  'P3'            'passed'
26680  'Kicukiro'    'Kigarama'  'P6'            'passed'
26635    'Gasabo'    'Rusororo'  'P5'            'passed'
28737  'Kicukiro'  'Nyarugunga'  'P3'            'passed'


In [ ]:
# let's check how many object type columns are left
print(df_team_1_unique.select_dtypes("object").columns)

It turns out that string columns are represented as object type!
we can now move on to the next stage in our data cleaning/engineering process

In [28]:
# Let's view the columns we have in our dataset
columns_df = df_team_1_unique.columns
print(*columns_df)

duration spv fo district sector school grade student_code eng_participation time_check_eng_1 p1_eng_q01_sub1 p1_eng_q01_sub2 p1_eng_q02_sub1 p1_eng_q02_sub2 p1_eng_q02_sub3 p1_eng_q03_sub1 p1_eng_q03_sub2 p1_eng_q03_sub3 p1_eng_q04_sub1 p1_eng_q04_sub2 p1_eng_q04_sub3 p1_eng_q05_sub1 p1_eng_q05_sub2 p1_eng_q05_sub3 p1_eng_q05_sub4 p1_eng_q05_sub5 p1_eng_q06_sub1 p1_eng_q06_sub2 p1_eng_q06_sub3 p1_eng_q07_sub1 p1_eng_q07_sub2 p1_eng_q07_sub3 p1_eng_q08_sub1 p1_eng_q08_sub2 p1_eng_q08_sub3 time_check_eng_2 p2_eng_q01_sub1 p2_eng_q01_sub2 p2_eng_q01_sub3 p2_eng_q01_sub4 p2_eng_q02_sub1 p2_eng_q02_sub2 p2_eng_q02_sub3 p2_eng_q03_sub1 p2_eng_q04_sub1 p2_eng_q05_sub1 p2_eng_q06_sub1 p2_eng_q07_sub1 p2_eng_q07_sub2 p2_eng_q08_sub1 p2_eng_q08_sub2 p2_eng_q08_sub3 p2_eng_q09_sub1 p2_eng_q09_sub2 p2_eng_q09_sub3 p2_eng_q10_sub1 p2_eng_q10_sub2 p2_eng_q10_sub3 p2_eng_q10_sub4 p2_eng_q11_sub1 time_check_eng_3 p3_eng_q01_sub1 p3_eng_q01_sub2 p3_eng_q02_sub1 p3_eng_q03_sub1 p3_eng_q04_sub1 p3_eng_q0

We are going to remove columns that are not important for the following steps

In [29]:
cols_remove = ['formdef_version',  'submissiondate', 'starttime', 'endtime',  'enddate']
df_long_1 = df_team_1_unique.copy()
df_long_1 = df_long_1.drop(cols_remove,axis=1)

##### Reshaping the dataset from Wide to Long

In [30]:
# from wide to long
timing_cols = [col for col in df_long_1 if col.startswith("time_check")]
time_math = [col for col in df_long_1 if col.startswith("time_check_math")]
time_eng = [col for col in df_long_1 if col.startswith("time_check_eng")]
time_kiny = [col for col in df_long_1 if col.startswith("time_check_kiny")]
id_variables = ['duration', 'spv', 'fo', 'district', 'sector', 'school', 'grade', 
                   'student_code', 'subdate', 'student_code_unsure'] + timing_cols
df_long_1 = pd.melt(df_long_1, id_vars= id_variables, 
                   var_name="questions", value_name="answers").reset_index()

In [31]:
# subset data that we can use to compare with team 2 data to check for discrepancies
df_long_sub_1 = df_long_1.drop(timing_cols + ["index","duration"], axis=1)
print(df_long_sub_1.columns)

Index(['spv', 'fo', 'district', 'sector', 'school', 'grade', 'student_code',
       'subdate', 'student_code_unsure', 'questions', 'answers'],
      dtype='object')


In [32]:
# setting global path
path_learnassess_year1 = "data/ipa-data/learning_assessment/data_entry/year1/clean"

In [33]:
# let's save the current dataset for future reference
df_long_sub_1.to_csv(f'{path_learnassess_year1}/first_entry/first_data_long_sub.csv',index=False)

We are now going to go thru the process for the second entry dataset 

In [34]:
data_entry_team_2.head()

deviceid devicephonenum username  \
0  04ff4e9b544ef4f3                 collect   
1  82e7dd08ca164eed                 collect   
2  90d67cc0f52bca6a                 collect   
3  fef81386406b2650                 collect   
4  1dd6117f9ca5748e                 collect   

                                         device_info duration caseid  \
0  samsung|SM-T225|13|SurveyCTO Collect 2.80.2 (2...      685          
1  TECNO|TECNO KC8|10|SurveyCTO Collect 2.80.2 (2...      354          
2  samsung|SM-T225|13|SurveyCTO Collect 2.80.2 (2...      203          
3  samsung|SM-T225|13|SurveyCTO Collect 2.80.2 (2...     1279          
4  samsung|SM-T225|13|SurveyCTO Collect 2.80.2 (2...      951          

                spv                    fo district    sector  ...  \
0  Uwimana  Pauline     Rushambara Alexis  Gatsibo    Muhura  ...   
1  Havugimana Saidi      Rusangwa Adolphe  Gakenke     Nemba  ...   
2  Havugimana Saidi       Alice Uwiduhaye     Huye  Ruhashya  ...   
3  Havugimana Saidi       Sandrine MAHORO  Gakenke  Kivuruga  ...   
4  Havugimana Saidi  DUSABIMANA Angelique  Gakenke  Kivuruga  ...   

  kin1marks_p6_kin1p6_kin_q021p6_k kin1marks_p6_kin1p6_kin_q061p6_k  \
0                              NaN                              NaN   
1                              NaN                              NaN   
2                              NaN                              NaN   
3                              NaN                              NaN   
4                              NaN                              NaN   

  kin1marks_p6_kin1p6_kin_q101p6_k v454      submissiondate  \
0                              NaN  NaN 2023-07-22 18:06:12   
1                              NaN  NaN 2023-07-24 17:57:22   
2                              NaN  NaN 2023-07-31 14:55:18   
3                              NaN  NaN 2023-07-24 07:42:06   
4                              NaN  NaN 2023-07-24 07:38:17   

            starttime             endtime    subdate    enddate v453  
0 2023-07-22 14:29:07 2023-07-22 14:40:32 2023-07-22 2023-07-22  NaN  
1 2023-07-24 15:35:32 2023-07-24 15:41:26 2023-07-24 2023-07-24  NaN  
2 2023-07-31 12:14:17 2023-07-31 12:17:40 2023-07-31 2023-07-31  NaN  
3 2023-07-22 13:36:34 2023-07-22 13:58:30 2023-07-24 2023-07-22  NaN  
4 2023-07-22 15:03:35 2023-07-22 15:19:41 2023-07-24 2023-07-22  NaN  

[5 rows x 456 columns]

In [35]:
data_entry_team_2.dropna(axis=1,how='all').describe(include=[np.number]).T

count          mean           std           min  \
p1_leg_cwpm_sub1   1680.0  1.100536e+01  9.915094e+00  0.000000e+00   
p2_leg_cwpm_sub1   1712.0  2.364194e+01  1.288926e+01  0.000000e+00   
p3_leg_cwpm_sub1   1647.0  3.568124e+01  1.478525e+01  0.000000e+00   
formdef_version   57431.0  2.402221e+09  2.175086e+07  2.307211e+09   

                           25%           50%           75%           max  
p1_leg_cwpm_sub1  0.000000e+00  1.000000e+01  2.000000e+01  2.700000e+01  
p2_leg_cwpm_sub1  1.600000e+01  2.500000e+01  3.500000e+01  4.100000e+01  
p3_leg_cwpm_sub1  2.700000e+01  3.600000e+01  4.700000e+01  5.900000e+01  
formdef_version   2.407201e+09  2.407201e+09  2.407201e+09  2.407201e+09

In [36]:
data_entry_team_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 57431 entries, 0 to 57430
Columns: 456 entries, deviceid to v453
dtypes: category(407), datetime64[ns](5), float64(10), object(34)
memory usage: 44.3+ MB


In [37]:
# check columns that are entirely empty
empty_cols_2 = [col for col in data_entry_team_2 if  data_entry_team_2[col].isna().all()]
print(empty_cols)

#drop empty cols
df_team_2 = data_entry_team_2.copy()
df_team_2 = df_team_2.drop(empty_cols,axis = 1)

# check columns that are entirely empty
empty_cols_20 = [col for col in df_team_2 if  df_team_2[col].isna().all()]
print(empty_cols_20)

['kin1marks_p6_kin1p6_kin_q021p6_k', 'kin1marks_p6_kin1p6_kin_q061p6_k', 'kin1marks_p6_kin1p6_kin_q101p6_k', 'v453', 'kin1marks_p5_kin1p5_kin_q141p5_k', 'v454']
[]


In [38]:
# let's check categorical columns
cat_cols0 = df_team_2.select_dtypes(["category"]).columns
print(cat_cols0)

Index(['spv', 'fo', 'eng_participation', 'p1_eng_q01_sub1', 'p1_eng_q01_sub2',
       'p1_eng_q02_sub1', 'p1_eng_q02_sub2', 'p1_eng_q02_sub3',
       'p1_eng_q03_sub1', 'p1_eng_q03_sub2',
       ...
       'p2_leg_q01_sub1', 'p2_leg_q02_sub1', 'p2_leg_q03_sub1',
       'p2_leg_q04_sub1', 'p2_leg_q05_sub1', 'p3_leg_q01_sub1',
       'p3_leg_q02_sub1', 'p3_leg_q03_sub1', 'p3_leg_q04_sub1',
       'p3_leg_q05_sub1'],
      dtype='object', length=407)


In [39]:
#let's check for one of the categorical columns the choices available:
print(dict(enumerate(df_team_2["p1_eng_q02_sub3"].cat.categories)))
print(dict(enumerate(df_team_2["eng_participation"].cat.categories)))
print(dict(enumerate(df_team_2["spv"].cat.categories)))
print(dict(enumerate(df_team_2["fo"].cat.categories)))

{0: 'Left blank', 1: 'No', 2: 'Yes'}
{0: 'No', 1: 'Yes'}
{0: 'Shema Christian', 1: 'NAHIMANA Reverien   ', 2: 'Havugimana Saidi', 3: 'Uwimana  Pauline', 4: 'NTAREMBA George   ', 5: 'Hatangimana Gisele'}
{0: 'Musabeyezu Noella ', 1: 'Rushambara Alexis', 2: 'NSHIMIYIMANA PASCAL', 3: 'Habonimana Gabriel', 4: 'Nirere Sandrine', 5: 'NIYIBIZI Leandre', 6: 'UWASE Francine\xa0', 7: 'Uwizeyimana Viateur', 8: 'Rusangwa Adolphe', 9: 'IRADUKUNDA GAHIRE ADOLPHE', 10: 'Ingabire Emelyne', 11: 'MUSHIMIRE Clarisse', 12: 'TUYISENGE ANICK', 13: 'Bagirishyaka Fulgence', 14: 'Fidele Iragena', 15: 'MUKANKOMEJE  Chantal', 16: 'NABAGIZE JUSTINE', 17: 'NTAWUSIGIRYAYO  Eric ', 18: 'IRAMBONA Valens', 19: 'Shingiro John', 20: 'UMUBYEYI MARIE GRACE', 21: 'MURAGIJIMANA Obadia', 22: 'UMUBYEYI Claudine', 23: 'DUFATANYE Devota', 24: 'NSHIMIYIMANA Bernard', 25: 'MUKANSANGA Jacqueline', 26: 'UWIMANA Jeannette', 27: 'NAHAYO Jean Damascene', 28: 'DUSENGUMUREMYI Yvonne', 29: 'NDIKUMWENAYO Epimaque', 30: 'DUHAWUMUGISHA Nath

In [40]:
enumerators = dict(enumerate(df_team_2["fo"].cat.categories))
enumerators = pd.DataFrame(enumerators.items(),columns=["codes", "names"])
enumerators.head(20)

codes                      names
0       0         Musabeyezu Noella 
1       1          Rushambara Alexis
2       2        NSHIMIYIMANA PASCAL
3       3         Habonimana Gabriel
4       4            Nirere Sandrine
5       5           NIYIBIZI Leandre
6       6            UWASE Francine 
7       7        Uwizeyimana Viateur
8       8           Rusangwa Adolphe
9       9  IRADUKUNDA GAHIRE ADOLPHE
10     10           Ingabire Emelyne
11     11         MUSHIMIRE Clarisse
12     12            TUYISENGE ANICK
13     13      Bagirishyaka Fulgence
14     14             Fidele Iragena
15     15       MUKANKOMEJE  Chantal
16     16           NABAGIZE JUSTINE
17     17      NTAWUSIGIRYAYO  Eric 
18     18            IRAMBONA Valens
19     19              Shingiro John

In [42]:
#we are going to convert categorical variables to their numeric values
df_team_2[cat_cols0] = df_team_2[cat_cols0].apply(lambda x: x.cat.codes)
#check the results
print(df_team_2.select_dtypes(["category"]).columns)
print(df_team_2["p1_eng_q02_sub3"].unique())
print(df_team_2["eng_participation"].unique())
print(df_team_2["spv"].unique())
print(df_team_2["fo"].unique())

Index([], dtype='object')
[-1  0  1  2]
[-1  1  0]
[3 2 5 4 1 0]
[  1   8 116 103  68 123  77 107  32  92 122 124  35  33  22  69  74  26
  18   2  36  70  49  30  20  65  56  10  58  24 114  19  13  80  47  15
   9  44  51 106 130  73  96 112 120  84  39  37  61  28  78  45  23  43
  46 104  85  12  41  75  71 108  67  34  62  72 105  94  54  83  87 101
 121  91  89   4  38  97  63  48 115  95   0   7 117  16  50  31 118   6
 100  90  11  60  93  14 127  27 129  59  55 125   3  66  29  21  81  52
  98 126  57  99  40 110 128 109  25  79 111   5  17  76 102  42 119  88
  82  64 113  86  53]


In [43]:
#check object type variables
object_cols = df_team_2.select_dtypes(["object"]).columns
print(object_cols)

Index(['deviceid', 'devicephonenum', 'username', 'device_info', 'duration',
       'caseid', 'district', 'sector', 'school', 'grade', 'student_code',
       'student_code_other', 'student_code_name', 'time_check_eng_1',
       'time_check_eng_2', 'time_check_eng_3', 'time_check_eng_4',
       'time_check_eng_5', 'time_check_eng_6', 'time_check_math_1',
       'time_check_math_2', 'time_check_math_3', 'time_check_math_4',
       'time_check_math_5', 'time_check_math_6', 'time_check_kiny_4',
       'time_check_kiny_5', 'time_check_kiny_6', 'time_check_kiny_1',
       'time_check_kiny_2', 'time_check_kiny_3', 'time_check_end',
       'instancename', 'key'],
      dtype='object')


In [44]:
#drop unuseful columns
df_team_2 = df_team_2.drop(['deviceid', 'devicephonenum', 'username', 'caseid','device_info','instancename', 'key'], axis=1)

In [45]:
#check object type variables again
object_cols0 = df_team_2.select_dtypes(["object"]).columns
print(object_cols0)

Index(['duration', 'district', 'sector', 'school', 'grade', 'student_code',
       'student_code_other', 'student_code_name', 'time_check_eng_1',
       'time_check_eng_2', 'time_check_eng_3', 'time_check_eng_4',
       'time_check_eng_5', 'time_check_eng_6', 'time_check_math_1',
       'time_check_math_2', 'time_check_math_3', 'time_check_math_4',
       'time_check_math_5', 'time_check_math_6', 'time_check_kiny_4',
       'time_check_kiny_5', 'time_check_kiny_6', 'time_check_kiny_1',
       'time_check_kiny_2', 'time_check_kiny_3', 'time_check_end'],
      dtype='object')


In [46]:
print(df_team_2["student_code"].unique())
print(df_team_2["student_code_name"].unique())
print(df_team_2["student_code_other"].unique())
print(df_team_2["time_check_eng_1"].unique())
print(df_team_2["time_check_end"].unique())

['530803230300' '421613220034' '241009230144' ... '531206190144'
 '320109200022' '531208200751']
['' 'Uwamahoro Clemantine' 'SHEMA Pascal' 'Iratuzi Nyiramahirwe'
 'Niyitanga Thegene' 'Mugwaneza Anitha' 'TUYISENGE Abraham'
 'Muhawenimana Diane' 'Irasubiza Richard' 'Nigirimbabazi jamus'
 'RUGWIRO MARIZA INES' 'Niyonshuti Theophile' 'Ufashijwenimana Jonathan'
 'Uwaremwe Centia' 'Igiraneza jacqueline' 'NEMA Mukombozi Emmanuel'
 'Byamungu Jesus' 'ISHIMWE Alpha' 'MUKUNZI ANICK IRUMVA'
 'Irumva Sano Sani Clety' 'Iradukunda delphine' 'KANYESIRYE Gift'
 'Kamikaze Alice' 'SENGA BERNADETTE' 'NDAYIZEYE Emmanuel'
 'Gisubizo gonna obrella' 'Iryikora Oreba' 'Shema sedric'
 'Irasubiza kenny' 'Izabayo Erneste' 'Isimbi Sangwa Liliane'
 'MUTUYIMANA Esther' 'Uwineza gloria' 'Ishimwe Irene delphine'
 'Manirakiza Faustin' 'Uwineza Angelique' 'Isimbi Kelia'
 'IHIMBAZWE ALPHA BRYAN' 'Niyomungeri j.Paul' 'NSHIMIYIMANA Jean Bosco'
 'SINJYENIYO FERDINAND' 'NYIRAMWIZA IRADUKUNDA' 'Uwikunda Henriette'
 'Niyonsenga

In [47]:
df_team_2[["student_code","student_code_other"]][df_team_2["student_code_other"]!="."]

student_code student_code_other
48     530814005068       530814005068
98     330534002020       330534002020
107    431104230104       431104230104
132      5410062002         5410062002
313    430506181060       430506181060
...             ...                ...
56804   42051400041        42051400041
57143  120402201051       120402201051
57261  420903005014              55555
57400  430506181189       430506181189
57407  210805002001       210805002001

[717 rows x 2 columns]

In [48]:
#Assigning values to student_code_other based on student_code variable
df_team_2.loc[df_team_2["student_code_other"] == df_team_2["student_code"], "student_code_other"] = "."
print(df_team_2.student_code_other.unique())

['.' '555' '55555' '421102210191' '0' '540712005002' '210504001001'
 '210504001002' '540712210425' '5555' '210504220334']


In [49]:
df_team_2.loc[df_team_2["student_code_other"] != ".", "student_code_other"].unique()

array(['555', '55555', '421102210191', '0', '540712005002',
       '210504001001', '210504001002', '540712210425', '5555',
       '210504220334'], dtype=object)

In [50]:
# let's create a column that will help us track these inconsistencies
df_team_2["student_code_unsure"] = np.where(df_team_2["student_code_other"].isin(['540712210384', '21108002025',
       '510712002010', '540712210425', '421807055001', '4305061550',
       '5707122003003', '4211020003025', '211001230088', '421102210191',
       '42111204027', '320028002001']),"flagged","passed")
print(df_team_2["student_code_unsure"].value_counts())

passed     57429
flagged        2
Name: student_code_unsure, dtype: int64


In [51]:
# check if student_code column is unique and doesn't have duplicates
df_team_2["student_code"].is_unique

False

In [52]:
# check how many dups we have
df_team_2["student_code"].duplicated().sum()

972

In [53]:
#let us view the duplicates
df_team_2[df_team_2["student_code"].isin(df_team_2["student_code"][df_team_2["student_code"].duplicated()])].sort_values(["student_code","submissiondate"])

duration  spv   fo district     sector  school grade  student_code  \
50866      172    5   73   Gasabo    Bumbogo  120108    P2  120108220685   
49973      193    5   73   Gasabo    Bumbogo  120108    P2  120108220685   
11751      390    5   73   Gasabo    Bumbogo  120108    P2  120108220960   
53581      254    5   73   Gasabo    Bumbogo  120108    P2  120108220960   
53145      375    3  123   Gasabo    Bumbogo  120127    P6  120127200483   
...        ...  ...  ...      ...        ...     ...   ...           ...   
14250      534    3   24  Kayonza  Rwinkwavu  541211    P3  541211200055   
39506      554    5   71  Kayonza  Rwinkwavu  541217    P4  541217200246   
19755      487    5   71  Kayonza  Rwinkwavu  541217    P4  541217200246   
48087      454    3  114   Nyanza  Nyagisozi  210911    P6  571028190472   
35636      272    1    6   Nyanza  Nyagisozi  210911    P6  571028190472   

      student_code_other student_code_name  ...  p3_leg_q04_sub1  \
50866                  .                    ...               -1   
49973                  .                    ...               -1   
11751                  .                    ...               -1   
53581                  .                    ...               -1   
53145                  .                    ...               -1   
...                  ...               ...  ...              ...   
14250                  .                    ...               -1   
39506                  .                    ...               -1   
19755                  .                    ...               -1   
48087                  .                    ...               -1   
35636                  .                    ...               -1   

      p3_leg_q05_sub1       time_check_end  formdef_version  \
50866              -1  2023-Aug-1 15:59:33     2.407201e+09   
49973              -1  2023-Aug-1 16:02:56     2.407201e+09   
11751              -1  2023-Aug-1 15:35:55     2.407201e+09   
53581              -1  2023-Aug-2 14:02:24     2.407201e+09   
53145              -1  2023-Aug-1 08:10:07     2.407201e+09   
...               ...                  ...              ...   
14250              -1  2023-Aug-2 15:23:34     2.407201e+09   
39506              -1  2023-Aug-3 08:51:19     2.407201e+09   
19755              -1  2023-Aug-3 08:59:34     2.407201e+09   
48087              -1  2023-Aug-4 16:39:40     2.407201e+09   
35636              -1  2023-Aug-7 11:44:42     2.407201e+09   

           submissiondate           starttime             endtime    subdate  \
50866 2023-08-01 16:12:17 2023-08-01 15:56:43 2023-08-01 15:59:35 2023-08-01   
49973 2023-08-01 16:12:18 2023-08-01 15:59:44 2023-08-01 16:02:58 2023-08-01   
11751 2023-08-01 16:12:26 2023-08-01 15:29:22 2023-08-01 15:35:57 2023-08-01   
53581 2023-08-02 15:22:06 2023-08-02 13:55:47 2023-08-02 14:02:26 2023-08-02   
53145 2023-08-01 15:32:32 2023-08-01 08:03:39 2023-08-01 08:10:08 2023-08-01   
...                   ...                 ...                 ...        ...   
14250 2023-08-02 15:51:24 2023-08-02 15:14:46 2023-08-02 15:23:42 2023-08-02   
39506 2023-08-03 16:11:04 2023-08-03 08:42:06 2023-08-03 08:51:20 2023-08-03   
19755 2023-08-03 16:11:05 2023-08-03 08:51:28 2023-08-03 08:59:35 2023-08-03   
48087 2023-08-04 17:45:19 2023-08-04 16:32:07 2023-08-04 16:39:41 2023-08-04   
35636 2023-08-07 13:00:06 2023-08-07 11:40:12 2023-08-07 11:44:45 2023-08-07   

         enddate  student_code_unsure  
50866 2023-08-01               passed  
49973 2023-08-01               passed  
11751 2023-08-01               passed  
53581 2023-08-02               passed  
53145 2023-08-01               passed  
...          ...                  ...  
14250 2023-08-02               passed  
39506 2023-08-03               passed  
19755 2023-08-03               passed  
48087 2023-08-04               passed  
35636 2023-08-07               passed  

[1906 rows x 444 columns]

In [54]:
df_team_2_unique = df_team_2.sort_values(["student_code","submissiondate"]).drop_duplicates("student_code",keep="last")
# check how many dups we have
print(df_team_2_unique["student_code"].duplicated().sum())

0


In [55]:
#changing column types to numeric, Datetime, and string

#numeric
df_team_2_unique[["duration","school","student_code"]] = df_team_2_unique[["duration","school","student_code"]].apply(pd.to_numeric)

In [56]:
#datetime
# select columns that starts with time_check
time_cols = [col for col in df_team_2_unique if col.startswith("time_check")]

df_team_2_unique[time_cols] = df_team_2_unique[time_cols].apply(pd.to_datetime)

In [57]:
# Let us look at how the datetime transformation was executed
df_team_2_unique[time_cols]

time_check_eng_1    time_check_eng_2    time_check_eng_3  \
5070  2023-08-14 14:44:34 2023-08-14 14:44:34 2023-08-14 14:44:34   
18076                 NaT                 NaT                 NaT   
43071 2023-07-31 14:58:34 2023-07-31 14:58:34 2023-07-31 14:58:34   
19923 2023-07-31 10:38:30 2023-07-31 10:38:30 2023-07-31 10:38:30   
14223 2023-08-02 10:12:54 2023-08-02 10:12:54 2023-08-02 10:12:54   
...                   ...                 ...                 ...   
36545 2023-08-02 15:21:12 2023-08-02 15:21:12 2023-08-02 15:21:12   
15758 2023-07-26 09:52:14 2023-07-26 09:52:14 2023-07-26 09:52:14   
54999 2023-08-03 11:37:53 2023-08-03 11:37:53 2023-08-03 11:37:53   
30930 2023-08-01 09:41:55 2023-08-01 09:41:55 2023-08-01 09:41:55   
27417 2023-08-04 08:31:26 2023-08-04 08:31:26 2023-08-04 08:31:26   

         time_check_eng_4    time_check_eng_5    time_check_eng_6  \
5070  2023-08-14 14:44:34 2023-08-14 14:46:11 2023-08-14 14:46:11   
18076                 NaT                 NaT                 NaT   
43071 2023-07-31 14:59:46 2023-07-31 14:59:46 2023-07-31 14:59:46   
19923 2023-07-31 10:38:30 2023-07-31 10:38:30 2023-07-31 10:38:30   
14223 2023-08-02 10:12:54 2023-08-02 10:12:54 2023-08-02 10:14:20   
...                   ...                 ...                 ...   
36545 2023-08-02 15:23:40 2023-08-02 15:23:40 2023-08-02 15:23:40   
15758 2023-07-26 09:52:14 2023-07-26 09:52:14 2023-07-26 09:55:06   
54999 2023-08-03 11:38:39 2023-08-03 11:38:39 2023-08-03 11:38:39   
30930 2023-08-01 09:41:55 2023-08-01 09:41:55 2023-08-01 09:41:55   
27417 2023-08-04 08:31:26 2023-08-04 08:33:28 2023-08-04 08:33:28   

        time_check_math_1   time_check_math_2   time_check_math_3  \
5070  2023-08-14 14:46:20 2023-08-14 14:46:20 2023-08-14 14:46:20   
18076                 NaT                 NaT                 NaT   
43071 2023-07-31 14:59:48 2023-07-31 14:59:48 2023-07-31 14:59:48   
19923 2023-07-31 10:40:00 2023-07-31 10:40:00 2023-07-31 10:40:00   
14223 2023-08-02 10:14:24 2023-08-02 10:14:24 2023-08-02 10:14:24   
...                   ...                 ...                 ...   
36545 2023-08-02 15:23:43 2023-08-02 15:23:43 2023-08-02 15:23:43   
15758 2023-07-26 09:55:10 2023-07-26 09:55:10 2023-07-26 09:55:10   
54999 2023-08-03 11:38:42 2023-08-03 11:38:42 2023-08-03 11:38:42   
30930 2023-08-01 09:43:12 2023-08-01 09:43:12 2023-08-01 09:43:12   
27417 2023-08-04 08:33:31 2023-08-04 08:33:31 2023-08-04 08:33:31   

        time_check_math_4   time_check_math_5   time_check_math_6  \
5070  2023-08-14 14:46:20 2023-08-14 14:48:01 2023-08-14 14:48:01   
18076                 NaT                 NaT                 NaT   
43071 2023-07-31 15:00:34 2023-07-31 15:00:34 2023-07-31 15:00:34   
19923 2023-07-31 10:40:00 2023-07-31 10:40:00 2023-07-31 10:40:00   
14223 2023-08-02 10:14:24 2023-08-02 10:14:24 2023-08-02 10:15:55   
...                   ...                 ...                 ...   
36545 2023-08-02 15:25:08 2023-08-02 15:25:08 2023-08-02 15:25:08   
15758 2023-07-26 09:55:10 2023-07-26 09:55:10 2023-07-26 09:56:27   
54999 2023-08-03 11:39:52 2023-08-03 11:39:52 2023-08-03 11:39:52   
30930 2023-08-01 09:43:12 2023-08-01 09:43:12 2023-08-01 09:43:12   
27417 2023-08-04 08:33:31 2023-08-04 08:35:06 2023-08-04 08:35:06   

        time_check_kiny_4   time_check_kiny_5   time_check_kiny_6  \
5070  2023-08-14 14:48:23 2023-08-14 14:51:10 2023-08-14 14:51:10   
18076                 NaT                 NaT                 NaT   
43071                 NaT                 NaT                 NaT   
19923 2023-07-31 10:42:11 2023-07-31 10:42:11 2023-07-31 10:42:11   
14223 2023-08-02 10:15:57 2023-08-02 10:15:57 2023-08-02 10:17:30   
...                   ...                 ...                 ...   
36545                 NaT                 NaT                 NaT   
15758 2023-07-26 09:56:29 2023-07-26 09:56:29 2023-07-26 09:57:58   
54999                 NaT                 NaT                 NaT   
309

In [58]:
# let's check how many object type columns are left
print(df_team_2_unique.select_dtypes("object").columns)

Index(['district', 'sector', 'grade', 'student_code_other',
       'student_code_name', 'student_code_unsure'],
      dtype='object')


In [59]:
# first we drop unwanted columns
unwanted_cols = ['student_code_other', 'student_code_name']
df_team_2_unique = df_team_2_unique.drop(unwanted_cols, axis=1)

In [60]:
# string
string_cols = ['district', 'sector', 'grade', 'student_code_unsure']

df_team_2_unique[string_cols] = df_team_2_unique[string_cols].apply(lambda col: col.map(repr)) 
print(df_team_2_unique[string_cols].head())

         district      sector grade student_code_unsure
5070    'Gakenke'    'Minazi'  'P4'            'passed'
18076   'Gakenke'    'Mataba'  'P4'            'passed'
43071  'Kicukiro'   'Kanombe'  'P3'            'passed'
19923  'Kicukiro'  'Kigarama'  'P6'            'passed'
14223    'Gasabo'  'Rusororo'  'P5'            'passed'


In [61]:
# Let's view the columns we have in our dataset
columns_df = df_team_2_unique.columns
print(*columns_df)

duration spv fo district sector school grade student_code eng_participation time_check_eng_1 p1_eng_q01_sub1 p1_eng_q01_sub2 p1_eng_q02_sub1 p1_eng_q02_sub2 p1_eng_q02_sub3 p1_eng_q03_sub1 p1_eng_q03_sub2 p1_eng_q03_sub3 p1_eng_q04_sub1 p1_eng_q04_sub2 p1_eng_q04_sub3 p1_eng_q05_sub1 p1_eng_q05_sub2 p1_eng_q05_sub3 p1_eng_q05_sub4 p1_eng_q05_sub5 p1_eng_q06_sub1 p1_eng_q06_sub2 p1_eng_q06_sub3 p1_eng_q07_sub1 p1_eng_q07_sub2 p1_eng_q07_sub3 p1_eng_q08_sub1 p1_eng_q08_sub2 p1_eng_q08_sub3 time_check_eng_2 p2_eng_q01_sub1 p2_eng_q01_sub2 p2_eng_q01_sub3 p2_eng_q01_sub4 p2_eng_q02_sub1 p2_eng_q02_sub2 p2_eng_q02_sub3 p2_eng_q03_sub1 p2_eng_q04_sub1 p2_eng_q05_sub1 p2_eng_q06_sub1 p2_eng_q07_sub1 p2_eng_q07_sub2 p2_eng_q08_sub1 p2_eng_q08_sub2 p2_eng_q08_sub3 p2_eng_q09_sub1 p2_eng_q09_sub2 p2_eng_q09_sub3 p2_eng_q10_sub1 p2_eng_q10_sub2 p2_eng_q10_sub3 p2_eng_q10_sub4 p2_eng_q11_sub1 time_check_eng_3 p3_eng_q01_sub1 p3_eng_q01_sub2 p3_eng_q02_sub1 p3_eng_q03_sub1 p3_eng_q04_sub1 p3_eng_q0

In [62]:
cols_remove = ['formdef_version',  'submissiondate', 'starttime', 'endtime',  'enddate']
df_long_2 = df_team_2_unique.copy()
df_long_2 = df_long_2.drop(cols_remove,axis=1)

In [63]:
# from wide to long
timing_cols = [col for col in df_long_2 if col.startswith("time_check")]
time_math = [col for col in df_long_2 if col.startswith("time_check_math")]
time_eng = [col for col in df_long_2 if col.startswith("time_check_eng")]
time_kiny = [col for col in df_long_2 if col.startswith("time_check_kiny")]
id_variables = ['duration', 'spv', 'fo', 'district', 'sector', 'school', 'grade', 
                   'student_code', 'subdate', 'student_code_unsure'] + timing_cols
df_long_2 = pd.melt(df_long_2, id_vars= id_variables, 
                   var_name="questions", value_name="answers").reset_index()

In [64]:
# subset data that we can use to compare with team 2 data to check for discrepancies
df_long_sub_2 = df_long_2.drop(timing_cols + ["index","duration"], axis=1)
print(df_long_sub_2.columns)

Index(['spv', 'fo', 'district', 'sector', 'school', 'grade', 'student_code',
       'subdate', 'student_code_unsure', 'questions', 'answers'],
      dtype='object')


In [65]:
# let's save the current dataset for future reference
df_long_sub_2.to_csv(f'{path_learnassess_year1}/second_entry/second_data_long_sub.csv',index=False)

We are going to inspect the reconciliation dataset

In [66]:
data_entry_reconciliation.head()

deviceid devicephonenum username  \
0  a4ef891f544f913c                 collect   
1  04ff4e9b544ef4f3                 collect   
2  fc25d174791055ee                 collect   
3  04ff4e9b544ef4f3                 collect   
4  04ff4e9b544ef4f3                 collect   

                                         device_info duration caseid  \
0  samsung|SM-T225|13|SurveyCTO Collect 2.80.2 (2...      123          
1  samsung|SM-T225|13|SurveyCTO Collect 2.80.2 (2...      164          
2  samsung|SM-T290|11|SurveyCTO Collect 2.80 (9b6...      174          
3  samsung|SM-T225|13|SurveyCTO Collect 2.80.2 (2...      258          
4  samsung|SM-T225|13|SurveyCTO Collect 2.80.2 (2...      203          

                         fo district   sector  school  ... p3_leg_q04_sub1  \
0  TUYISHIMIRE Marie Claire   Gasabo  Bumbogo  120108  ...             NaN   
1         Rushambara Alexis   Gasabo  Bumbogo  120108  ...             NaN   
2       NSHIMIYIMANA PASCAL   Gasabo  Bumbogo  120108  ...             NaN   
3         Rushambara Alexis   Gasabo  Bumbogo  120108  ...             NaN   
4         Rushambara Alexis   Gasabo  Bumbogo  120108  ...             NaN   

   p3_leg_q05_sub1            instancename formdef_version  \
0              NaN  student_id120108140063    2.308101e+09   
1              NaN  student_id120108140081    2.308101e+09   
2              NaN  student_id120108140186    2.308101e+09   
3              NaN  student_id120108160780    2.308101e+09   
4              NaN  student_id120108171624    2.308101e+09   

                                         key      submissiondate  \
0  uuid:c68dac3d-0236-48da-b7e4-1cd079bbacee 2023-08-11 16:46:37   
1  uuid:bdf9beee-3d50-4cef-9c77-6fbe1a8767aa 2023-08-11 16:51:12   
2  uuid:4186881a-f440-4daa-a4b1-f958331ab9e1 2023-08-11 16:50:45   
3  uuid:db93fd73-3674-4b48-87ac-5abe636a4a24 2023-08-11 16:51:12   
4  uuid:dd54ee09-4eec-41dd-ac8d-659aacd0fcea 2023-08-11 16:51:13   

            starttime             endtime    subdate    enddate  
0 2023-08-11 10:07:29 2023-08-11 10:09:32 2023-08-11 2023-08-11  
1 2023-08-11 10:42:32 2023-08-11 10:45:16 2023-08-11 2023-08-11  
2 2023-08-11 09:20:15 2023-08-11 09:23:08 2023-08-11 2023-08-11  
3 2023-08-11 10:34:25 2023-08-11 10:38:43 2023-08-11 2023-08-11  
4 2023-08-11 10:01:51 2023-08-11 10:05:14 2023-08-11 2023-08-11  

[5 rows x 636 columns]

In [68]:
print(*data_entry_reconciliation.columns)

deviceid devicephonenum username device_info duration caseid fo district sector school grade student_code school_student discrepancy_count discrepancy_index_1 discrepancy_question_id_1 discrepancy_index_2 discrepancy_question_id_2 discrepancy_index_3 discrepancy_question_id_3 discrepancy_index_4 discrepancy_question_id_4 discrepancy_index_5 discrepancy_question_id_5 discrepancy_index_6 discrepancy_question_id_6 discrepancy_index_7 discrepancy_question_id_7 discrepancy_index_8 discrepancy_question_id_8 discrepancy_index_9 discrepancy_question_id_9 discrepancy_index_10 discrepancy_question_id_10 discrepancy_index_11 discrepancy_question_id_11 discrepancy_index_12 discrepancy_question_id_12 discrepancy_index_13 discrepancy_question_id_13 discrepancy_index_14 discrepancy_question_id_14 discrepancy_index_15 discrepancy_question_id_15 discrepancy_index_16 discrepancy_question_id_16 discrepancy_index_17 discrepancy_question_id_17 discrepancy_index_18 discrepancy_question_id_18 discrepancy_ind

In [69]:
# let's check columns that start with discrepancy
discr_columns = [col for col in data_entry_reconciliation if col.startswith("discrepancy")]
data_entry_reconciliation[discr_columns]

discrepancy_count discrepancy_index_1 discrepancy_question_id_1  \
0                   100       discrepancy_1           p1_eng_q04_sub3   
1                   100       discrepancy_1         p6_kin_q10_sub2_1   
2                   100       discrepancy_1         p4_mat_q01_sub1_1   
3                   100       discrepancy_1           p6_mat_q08_sub1   
4                   100       discrepancy_1         p6_mat_q02_sub1_4   
...                 ...                 ...                       ...   
52271               100       discrepancy_1           p2_eng_q09_sub2   
52272               100       discrepancy_1           p2_eng_q09_sub2   
52273               100       discrepancy_1           p1_eng_q01_sub2   
52274               100       discrepancy_1           p2_mat_q01_sub1   
52275               100       discrepancy_1           p6_kin_q01_sub2   

      discrepancy_index_2 discrepancy_question_id_2 discrepancy_index_3  \
0           discrepancy_2           p1_eng_q04_sub2       discrepancy_3   
1           discrepancy_2           p6_mat_q02_sub2       discrepancy_3   
2           discrepancy_2         p4_mat_q01_sub1_2       discrepancy_3   
3           discrepancy_2         p6_mat_q02_sub1_4       discrepancy_3   
4           discrepancy_2           p6_kin_q01_sub2       discrepancy_3   
...                   ...                       ...                 ...   
52271       discrepancy_2           p2_eng_q09_sub3       discrepancy_3   
52272       discrepancy_2           p2_eng_q09_sub3       discrepancy_3   
52273       discrepancy_2           p1_mat_q06_sub3       discrepancy_3   
52274       discrepancy_2           p2_eng_q09_sub3       discrepancy_3   
52275       discrepancy_2           p6_eng_q06_sub4       discrepancy_3   

      discrepancy_question_id_3 discrepancy_index_4 discrepancy_question_id_4  \
0               p1_mat_q08_sub1       discrepancy_4           p1_mat_q09_sub1   
1             p6_mat_q03_sub2_1       discrepancy_4         p6_kin_q06_sub2_1   
2             p4_mat_q01_sub1_3       discrepancy_4         p4_kin_q09_sub1_1   
3               p6_eng_q06_sub4       discrepancy_4         p6_kin_q06_sub1_2   
4               p6_mat_q05_sub1       discrepancy_4         p6_mat_q02_sub1_1   
...                         ...                 ...                       ...   
52271           p2_eng_q07_sub2       discrepancy_4                             
52272           p2_mat_q06_sub3       discrepancy_4           p2_mat_q01_sub1   
52273           p1_eng_q01_sub1       discrepancy_4                             
52274                                 discrepancy_4                             
52275           p6_eng_q01_sub1       discrepancy_4         p6_kin_q06_sub1_2   

      discrepancy_index_5  ... discrepancy_question_id_96  \
0           discrepancy_5  ...                              
1           discrepancy_5  ...                              
2           discrepancy_5  ...                              
3           discrepancy_5  ...                              
4           discrepancy_5  ...                              
...                   ...  ...                        ...   
52271       discrepancy_5  ...                              
52272       discrepancy_5  ...                              
52273       discrepancy_5  ...                              
52274       discrepancy_5  ...                              
52275       discrepancy_5  ...                              

      discrepancy_index_97 discrepancy_question_id_97 discrepancy_index_98  \
0           discrepancy_97                                  discrepancy_98   
1           discrepancy_97                                  discrepancy_98   
2           discrepancy_97                                  discrepancy_98   
3           discrepancy_97                                  discrepancy_98   
4           discrepancy_97                                  discrepancy_98   
...                    ...                        ... 

In [70]:
# we are going to remove the discrepancy variables
data_entry_reconciliation = data_entry_reconciliation.drop(discr_columns, axis=1)
data_entry_reconciliation.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 52276 entries, 0 to 52275
Columns: 434 entries, deviceid to enddate
dtypes: category(411), datetime64[ns](5), float64(5), object(13)
memory usage: 30.2+ MB


In [71]:
print(*data_entry_reconciliation.columns)

deviceid devicephonenum username device_info duration caseid fo district sector school grade student_code school_student eng_participation p1_eng_q01_sub1 p1_eng_q01_sub2 p1_eng_q02_sub1 p1_eng_q02_sub2 p1_eng_q02_sub3 p1_eng_q03_sub1 p1_eng_q03_sub2 p1_eng_q03_sub3 p1_eng_q04_sub1 p1_eng_q04_sub2 p1_eng_q04_sub3 p1_eng_q05_sub1 p1_eng_q05_sub2 p1_eng_q05_sub3 p1_eng_q05_sub4 p1_eng_q05_sub5 p1_eng_q06_sub1 p1_eng_q06_sub2 p1_eng_q06_sub3 p1_eng_q07_sub1 p1_eng_q07_sub2 p1_eng_q07_sub3 p1_eng_q08_sub1 p1_eng_q08_sub2 p1_eng_q08_sub3 p2_eng_q01_sub1 p2_eng_q01_sub2 p2_eng_q01_sub3 p2_eng_q01_sub4 p2_eng_q02_sub1 p2_eng_q02_sub2 p2_eng_q02_sub3 p2_eng_q03_sub1 p2_eng_q04_sub1 p2_eng_q05_sub1 p2_eng_q06_sub1 p2_eng_q07_sub1 p2_eng_q07_sub2 p2_eng_q08_sub1 p2_eng_q08_sub2 p2_eng_q08_sub3 p2_eng_q09_sub1 p2_eng_q09_sub2 p2_eng_q09_sub3 p2_eng_q10_sub1 p2_eng_q10_sub2 p2_eng_q10_sub3 p2_eng_q10_sub4 p2_eng_q11_sub1 p3_eng_q01_sub1 p3_eng_q01_sub2 p3_eng_q02_sub1 p3_eng_q03_sub1 p3_eng_q04_su

In [72]:
# remove other unnecessary columns
unn_columns = ['deviceid', 'devicephonenum', 'username', 'device_info', 'caseid', 'school_student', 'instancename', 'formdef_version', 'key', 'submissiondate', 'starttime', 'endtime', 'enddate']

data_entry_reconciliation = data_entry_reconciliation.drop(unn_columns, axis=1)
data_entry_reconciliation.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 52276 entries, 0 to 52275
Columns: 421 entries, duration to subdate
dtypes: category(411), datetime64[ns](1), float64(4), object(5)
memory usage: 25.0+ MB


In [73]:
# view dataset
data_entry_reconciliation.head()

duration                        fo district   sector  school grade  \
0      123  TUYISHIMIRE Marie Claire   Gasabo  Bumbogo  120108    P1   
1      164         Rushambara Alexis   Gasabo  Bumbogo  120108    P6   
2      174       NSHIMIYIMANA PASCAL   Gasabo  Bumbogo  120108    P4   
3      258         Rushambara Alexis   Gasabo  Bumbogo  120108    P6   
4      203         Rushambara Alexis   Gasabo  Bumbogo  120108    P6   

   student_code eng_participation p1_eng_q01_sub1 p1_eng_q01_sub2  ...  \
0  1.201081e+11               NaN             NaN             NaN  ...   
1  1.201081e+11               NaN             NaN             NaN  ...   
2  1.201081e+11               NaN             NaN             NaN  ...   
3  1.201082e+11               NaN             NaN             NaN  ...   
4  1.201082e+11               NaN             NaN             NaN  ...   

  p2_leg_q03_sub1 p2_leg_q04_sub1 p2_leg_q05_sub1 p3_leg_cwpm_sub1  \
0             NaN             NaN             NaN              NaN   
1             NaN             NaN             NaN              NaN   
2             NaN             NaN             NaN              NaN   
3             NaN             NaN             NaN              NaN   
4             NaN             NaN             NaN              NaN   

  p3_leg_q01_sub1 p3_leg_q02_sub1 p3_leg_q03_sub1 p3_leg_q04_sub1  \
0             NaN             NaN             NaN             NaN   
1             NaN             NaN             NaN             NaN   
2             NaN             NaN             NaN             NaN   
3             NaN             NaN             NaN             NaN   
4             NaN             NaN             NaN             NaN   

  p3_leg_q05_sub1    subdate  
0             NaN 2023-08-11  
1             NaN 2023-08-11  
2             NaN 2023-08-11  
3             NaN 2023-08-11  
4             NaN 2023-08-11  

[5 rows x 421 columns]

In [74]:
# check columns that are entirely empty
empty_cols = [col for col in data_entry_reconciliation if  data_entry_reconciliation[col].isna().all()]
print(empty_cols)

['p5_kin_q14_sub1_3', 'p6_kin_q02_sub1_3', 'p6_kin_q06_sub1_3', 'p6_kin_q10_sub1_3', 'p6_kin_q10_sub2_3']


In [75]:
#drop empty cols
df_rec = data_entry_reconciliation.copy()
df_rec = df_rec.drop(empty_cols,axis = 1)

# check columns that are entirely empty
empty_cols0 = [col for col in df_rec if  df_rec[col].isna().all()]
print(empty_cols0)

[]


In [76]:
# let's check categorical columns
cat_cols0 = df_rec.select_dtypes(["category"]).columns
print(cat_cols0)

Index(['fo', 'eng_participation', 'p1_eng_q01_sub1', 'p1_eng_q01_sub2',
       'p1_eng_q02_sub1', 'p1_eng_q02_sub2', 'p1_eng_q02_sub3',
       'p1_eng_q03_sub1', 'p1_eng_q03_sub2', 'p1_eng_q03_sub3',
       ...
       'p2_leg_q01_sub1', 'p2_leg_q02_sub1', 'p2_leg_q03_sub1',
       'p2_leg_q04_sub1', 'p2_leg_q05_sub1', 'p3_leg_q01_sub1',
       'p3_leg_q02_sub1', 'p3_leg_q03_sub1', 'p3_leg_q04_sub1',
       'p3_leg_q05_sub1'],
      dtype='object', length=406)


In [78]:
print(dict(enumerate(df_rec["p1_eng_q02_sub3"].cat.categories)))
print(dict(enumerate(df_rec["eng_participation"].cat.categories)))
print(dict(enumerate(df_rec["fo"].cat.categories)))

{0: 'Left blank', 1: 'No', 2: 'Yes'}
{0: 'No', 1: 'Yes'}
{0: 'Musabeyezu Noella ', 1: 'Rushambara Alexis', 2: 'NSHIMIYIMANA PASCAL', 3: 'Habonimana Gabriel', 4: 'Nirere Sandrine', 5: 'NIYIBIZI Leandre', 6: 'UWASE Francine\xa0', 7: 'Uwizeyimana Viateur', 8: 'Rusangwa Adolphe', 9: 'IRADUKUNDA GAHIRE ADOLPHE', 10: 'Ingabire Emelyne', 11: 'MUSHIMIRE Clarisse', 12: 'Mudahogora Placidie', 13: 'TUYISENGE ANICK', 14: 'Bagirishyaka Fulgence', 15: 'Fidele Iragena', 16: 'MUKANKOMEJE  Chantal', 17: 'NABAGIZE JUSTINE', 18: 'NTAWUSIGIRYAYO  Eric ', 19: 'Shingiro John', 20: 'UMUBYEYI MARIE GRACE', 21: 'MURAGIJIMANA Obadia', 22: 'MASENGESHO Samuel', 23: 'UMUBYEYI Claudine', 24: 'DUFATANYE Devota', 25: 'NSHIMIYIMANA Bernard', 26: 'MUKANSANGA Jacqueline', 27: 'UWIMANA Jeannette', 28: 'NAHAYO Jean Damascene', 29: 'DUSENGUMUREMYI Yvonne', 30: 'NSENGUMUREMYI Felix', 31: 'NDIKUMWENAYO Epimaque', 32: 'DUHAWUMUGISHA Nathan', 33: 'GATETE Fred', 34: 'MUTUYIMANA Josephine', 35: 'KAVAMAHANGA Lambert', 36: 'AENGAM

In [79]:
enumerators = dict(enumerate(df_rec["fo"].cat.categories))
enumerators = pd.DataFrame(enumerators.items(),columns=["codes", "names"])
enumerators.head(20)

codes                      names
0       0         Musabeyezu Noella 
1       1          Rushambara Alexis
2       2        NSHIMIYIMANA PASCAL
3       3         Habonimana Gabriel
4       4            Nirere Sandrine
5       5           NIYIBIZI Leandre
6       6            UWASE Francine 
7       7        Uwizeyimana Viateur
8       8           Rusangwa Adolphe
9       9  IRADUKUNDA GAHIRE ADOLPHE
10     10           Ingabire Emelyne
11     11         MUSHIMIRE Clarisse
12     12        Mudahogora Placidie
13     13            TUYISENGE ANICK
14     14      Bagirishyaka Fulgence
15     15             Fidele Iragena
16     16       MUKANKOMEJE  Chantal
17     17           NABAGIZE JUSTINE
18     18      NTAWUSIGIRYAYO  Eric 
19     19              Shingiro John

In [80]:
#we are going to convert categorical variables to their numeric values
df_rec[cat_cols0] = df_rec[cat_cols0].apply(lambda x: x.cat.codes)
#check the results
print(df_rec.select_dtypes(["category"]).columns)
print(df_rec["p1_eng_q02_sub3"].unique())
print(df_rec["eng_participation"].unique())
print(df_rec["fo"].unique())

Index([], dtype='object')
[-1  0  2  1]
[-1  1  0]
[ 60   1   2  82  17  65  37  76 125  77   9  66  79   4  62  14  40  24
  80  10  51  49 102 107  11 132   5 123  22  73  30  97  48  63  81  16
  39  46  25 129  53 121 120   8  56  27 133 111 112 118 128  47 110  41
 106  75  57  18  89  98 101  78  64  32  50  69  42  92  55  88 103  26
 108   0  19 124 126  36  35  23  34  90  38  21 105  85  74  59  58  13
 134 100  31 117  15  54  61  72  71 109 122  45  20 114  68 127 115  84
  12  94  93  67 113 116  87  86   7  28  83  33   6 131  52 104  95  96
 130 119  43  99  44   3  29  91  70 135]


In [81]:
df_rec.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 52276 entries, 0 to 52275
Columns: 416 entries, duration to subdate
dtypes: datetime64[ns](1), float64(4), int16(1), int8(405), object(5)
memory usage: 24.7+ MB


In [82]:
#check object type variables
object_cols = df_rec.select_dtypes(["object"]).columns
print(object_cols)


Index(['duration', 'district', 'sector', 'school', 'grade'], dtype='object')


In [83]:
# check if student_code column is unique and doesn't have duplicates
df_rec["student_code"].is_unique

True

In [84]:
#changing column types to numeric, Datetime, and string

#numeric
df_rec[["duration","school"]] = df_rec[["duration","school"]].apply(pd.to_numeric)

In [85]:
# string
string_cols = ['district', 'sector', 'grade']

df_rec[string_cols] = df_rec[string_cols].apply(lambda col: col.map(repr)) #interesting
print(df_rec[string_cols].head())

   district     sector grade
0  'Gasabo'  'Bumbogo'  'P1'
1  'Gasabo'  'Bumbogo'  'P6'
2  'Gasabo'  'Bumbogo'  'P4'
3  'Gasabo'  'Bumbogo'  'P6'
4  'Gasabo'  'Bumbogo'  'P6'


In [86]:
# Let's view the columns we have in our dataset
columns_df = df_rec.columns
print(*columns_df)

duration fo district sector school grade student_code eng_participation p1_eng_q01_sub1 p1_eng_q01_sub2 p1_eng_q02_sub1 p1_eng_q02_sub2 p1_eng_q02_sub3 p1_eng_q03_sub1 p1_eng_q03_sub2 p1_eng_q03_sub3 p1_eng_q04_sub1 p1_eng_q04_sub2 p1_eng_q04_sub3 p1_eng_q05_sub1 p1_eng_q05_sub2 p1_eng_q05_sub3 p1_eng_q05_sub4 p1_eng_q05_sub5 p1_eng_q06_sub1 p1_eng_q06_sub2 p1_eng_q06_sub3 p1_eng_q07_sub1 p1_eng_q07_sub2 p1_eng_q07_sub3 p1_eng_q08_sub1 p1_eng_q08_sub2 p1_eng_q08_sub3 p2_eng_q01_sub1 p2_eng_q01_sub2 p2_eng_q01_sub3 p2_eng_q01_sub4 p2_eng_q02_sub1 p2_eng_q02_sub2 p2_eng_q02_sub3 p2_eng_q03_sub1 p2_eng_q04_sub1 p2_eng_q05_sub1 p2_eng_q06_sub1 p2_eng_q07_sub1 p2_eng_q07_sub2 p2_eng_q08_sub1 p2_eng_q08_sub2 p2_eng_q08_sub3 p2_eng_q09_sub1 p2_eng_q09_sub2 p2_eng_q09_sub3 p2_eng_q10_sub1 p2_eng_q10_sub2 p2_eng_q10_sub3 p2_eng_q10_sub4 p2_eng_q11_sub1 p3_eng_q01_sub1 p3_eng_q01_sub2 p3_eng_q02_sub1 p3_eng_q03_sub1 p3_eng_q04_sub1 p3_eng_q04_sub2 p3_eng_q04_sub3 p3_eng_q04_sub4 p3_eng_q05_sub1 

In [87]:
# from wide to long

id_variables = ['duration', 'fo', 'district', 'sector', 'school', 'grade', 
                   'student_code', 'subdate']
df_rec_long = pd.melt(df_rec, id_vars= id_variables, 
                   var_name="questions", value_name="correct_answers").reset_index()

In [88]:
df_rec_long.head()

index  duration  fo  district     sector  school grade  student_code  \
0      0       123  60  'Gasabo'  'Bumbogo'  120108  'P1'  1.201081e+11   
1      1       164   1  'Gasabo'  'Bumbogo'  120108  'P6'  1.201081e+11   
2      2       174   2  'Gasabo'  'Bumbogo'  120108  'P4'  1.201081e+11   
3      3       258   1  'Gasabo'  'Bumbogo'  120108  'P6'  1.201082e+11   
4      4       203   1  'Gasabo'  'Bumbogo'  120108  'P6'  1.201082e+11   

     subdate          questions  correct_answers  
0 2023-08-11  eng_participation             -1.0  
1 2023-08-11  eng_participation             -1.0  
2 2023-08-11  eng_participation             -1.0  
3 2023-08-11  eng_participation             -1.0  
4 2023-08-11  eng_participation             -1.0

In [89]:
# subset data that we can use to compare with both teams data to check for enumerators that were correct
df_rec_long_sub = df_rec_long.drop(["index","duration"], axis=1)
print(df_rec_long_sub.columns)

Index(['fo', 'district', 'sector', 'school', 'grade', 'student_code',
       'subdate', 'questions', 'correct_answers'],
      dtype='object')


In [90]:
# let's save the current dataset for future reference
df_rec_long_sub.to_csv(f'{path_learnassess_year1}/reconciliation/reconc_data_long_sub.csv',index=False)

## Discrepancies Check

In [4]:
# import datasets to use

# setting global path
path_learnassess_year1 = "data/ipa-data/learning_assessment/data_entry/year1/clean"

# we start by using data entry data from year 1

first_data_long_sub = pd.read_csv(f'{path_learnassess_year1}/first_entry/first_data_long_sub.csv')
second_data_long_sub = pd.read_csv(f'{path_learnassess_year1}/second_entry/second_data_long_sub.csv')
reconc_data_long_sub = pd.read_csv(f'{path_learnassess_year1}/reconciliation/reconc_data_long_sub.csv')

print(first_data_long_sub.head())

   spv  fo    district        sector  school grade  student_code     subdate  \
0    2  35  'Kicukiro'     'Gikondo'  130313  'P2'  1.303130e-01  2023-08-19   
1    0  74  'Kicukiro'     'Kanombe'  130532  'P3'  1.101032e+11  2023-08-01   
2    1  21  'Kicukiro'    'Kigarama'  130717  'P6'  1.101042e+11  2023-08-01   
3    0  76    'Gasabo'    'Rusororo'  121431  'P5'  1.102012e+11  2023-08-03   
4    0  95  'Kicukiro'  'Nyarugunga'  131007  'P3'  1.102012e+11  2023-08-02   

  student_code_unsure          questions  answers  
0            'passed'  eng_participation      1.0  
1            'passed'  eng_participation      1.0  
2            'passed'  eng_participation      1.0  
3            'passed'  eng_participation      1.0  
4            'passed'  eng_participation      1.0  


In [6]:
# let's also check team 2 and reconciliation columns
print(f'Team 2 columns: {second_data_long_sub.columns}\n')
print(f'Reconciliation columns: {reconc_data_long_sub.columns}\n')

Team 2 columns: Index(['spv', 'fo', 'district', 'sector', 'school', 'grade', 'student_code',
       'subdate', 'student_code_unsure', 'questions', 'answers'],
      dtype='object')

Reconciliation columns: Index(['fo', 'district', 'sector', 'school', 'grade', 'student_code',
       'subdate', 'questions', 'correct_answers'],
      dtype='object')



In [5]:
# let's rename columns to avoid confusion when we merge datasets

#team 1
first_data_long_sub = first_data_long_sub.rename({'spv': 'spv_first',
                                                  'fo' : 'fo_first',
                                                  'subdate': 'subdate_first',
                                                  'answers': 'answers_first'}, axis = 1)

#team 2
second_data_long_sub = second_data_long_sub.rename({'spv': 'spv_second',
                                                    'fo' : 'fo_second',
                                                    'subdate': 'subdate_second',
                                                    'student_code_unsure': 'student_unsure_second',
                                                    'answers': 'answers_second'}, axis = 1)

#reconciliation
reconc_data_long_sub = reconc_data_long_sub.rename({'fo' : 'fo_rec',
                                                    'subdate' : 'subdate_rec'}, axis = 1)

print(f'Team 1 columns: {first_data_long_sub.columns}\n')
print(f'Team 2 columns: {second_data_long_sub.columns}\n')
print(f'Reconciliation columns: {reconc_data_long_sub.columns}\n')

Team 1 columns: Index(['spv_first', 'fo_first', 'district', 'sector', 'school', 'grade',
       'student_code', 'subdate_first', 'student_code_unsure', 'questions',
       'answers_first'],
      dtype='object')

Team 2 columns: Index(['spv_second', 'fo_second', 'district', 'sector', 'school', 'grade',
       'student_code', 'subdate_second', 'student_unsure_second', 'questions',
       'answers_second'],
      dtype='object')

Reconciliation columns: Index(['fo_rec', 'district', 'sector', 'school', 'grade', 'student_code',
       'subdate_rec', 'questions', 'correct_answers'],
      dtype='object')



In [6]:
# we are going to merge the 3 datasets 
unique_cols = ['district', 'sector', 'school', 'grade', 'student_code', 'questions']
dfs = [first_data_long_sub, second_data_long_sub, reconc_data_long_sub]
df_merged = ft.reduce(lambda left, right: pd.merge(left, right, on = unique_cols, how = 'outer'), dfs)
df_merged.head()

spv_first  fo_first    district        sector  school grade  student_code  \
0        2.0      35.0  'Kicukiro'     'Gikondo'  130313  'P2'  1.303130e-01   
1        0.0      74.0  'Kicukiro'     'Kanombe'  130532  'P3'  1.101032e+11   
2        1.0      21.0  'Kicukiro'    'Kigarama'  130717  'P6'  1.101042e+11   
3        0.0      76.0    'Gasabo'    'Rusororo'  121431  'P5'  1.102012e+11   
4        0.0      95.0  'Kicukiro'  'Nyarugunga'  131007  'P3'  1.102012e+11   

  subdate_first student_code_unsure          questions  answers_first  \
0    2023-08-19            'passed'  eng_participation            1.0   
1    2023-08-01            'passed'  eng_participation            1.0   
2    2023-08-01            'passed'  eng_participation            1.0   
3    2023-08-03            'passed'  eng_participation            1.0   
4    2023-08-02            'passed'  eng_participation            1.0   

   spv_second  fo_second subdate_second student_unsure_second  answers_second  \
0         NaN        NaN            NaN                   NaN             NaN   
1         5.0       75.0     2023-07-31              'passed'             1.0   
2         3.0        8.0     2023-07-31              'passed'             1.0   
3         3.0      107.0     2023-08-02              'passed'             1.0   
4         5.0       35.0     2023-08-01              'passed'             1.0   

   fo_rec subdate_rec  correct_answers  
0     NaN         NaN              NaN  
1   121.0  2023-08-12             -1.0  
2   126.0  2023-08-11             -1.0  
3    79.0  2023-08-11             -1.0  
4    49.0  2023-08-12             -1.0

In [7]:
df_merged.tail(15)

spv_first  fo_first   district    sector  school grade  \
23195601        NaN       NaN  'Musanze'  'Kinigi'  430704  'P3'   
23195602        NaN       NaN  'Musanze'  'Kinigi'  430704  'P3'   
23195603        NaN       NaN  'Musanze'  'Kinigi'  430704  'P3'   
23195604        NaN       NaN  'Musanze'  'Kinigi'  430704  'P3'   
23195605        NaN       NaN  'Musanze'  'Kinigi'  430704  'P3'   
23195606        NaN       NaN  'Musanze'  'Kinigi'  430704  'P3'   
23195607        NaN       NaN  'Musanze'  'Kinigi'  430704  'P3'   
23195608        NaN       NaN  'Musanze'  'Kinigi'  430704  'P3'   
23195609        NaN       NaN  'Musanze'  'Kinigi'  430704  'P3'   
23195610        NaN       NaN  'Musanze'  'Kinigi'  430704  'P3'   
23195611        NaN       NaN  'Musanze'  'Kinigi'  430704  'P3'   
23195612        NaN       NaN  'Musanze'  'Kinigi'  430704  'P3'   
23195613        NaN       NaN  'Musanze'  'Kinigi'  430704  'P3'   
23195614        NaN       NaN  'Musanze'  'Kinigi'  430704  'P3'   
23195615        NaN       NaN  'Musanze'  'Kinigi'  430704  'P3'   

          student_code subdate_first student_code_unsure         questions  \
23195601  4.307042e+11           NaN                 NaN   p2_leg_q04_sub1   
23195602  4.307042e+11           NaN                 NaN   p2_leg_q05_sub1   
23195603  4.307042e+11           NaN                 NaN   p2_leg_q05_sub1   
23195604  4.307042e+11           NaN                 NaN  p3_leg_cwpm_sub1   
23195605  4.307042e+11           NaN                 NaN  p3_leg_cwpm_sub1   
23195606  4.307042e+11           NaN                 NaN   p3_leg_q01_sub1   
23195607  4.307042e+11           NaN                 NaN   p3_leg_q01_sub1   
23195608  4.307042e+11           NaN                 NaN   p3_leg_q02_sub1   
23195609  4.307042e+11           NaN                 NaN   p3_leg_q02_sub1   
23195610  4.307042e+11           NaN                 NaN   p3_leg_q03_sub1   
23195611  4.307042e+11           NaN                 NaN   p3_leg_q03_sub1   
23195612  4.307042e+11           NaN                 NaN   p3_leg_q04_sub1   
23195613  4.307042e+11           NaN                 NaN   p3_leg_q04_sub1   
23195614  4.307042e+11           NaN                 NaN   p3_leg_q05_sub1   
23195615  4.307042e+11           NaN                 NaN   p3_leg_q05_sub1   

          answers_first  spv_second  fo_second subdate_second  \
23195601            NaN         NaN        NaN            NaN   
23195602            NaN         NaN        NaN            NaN   
23195603            NaN         NaN        NaN            NaN   
23195604            NaN         NaN        NaN            NaN   
23195605            NaN         NaN        NaN            NaN   
23195606            NaN         NaN        NaN            NaN   
23195607            NaN         NaN        NaN            NaN   
23195608            NaN         NaN        NaN            NaN   
23195609            NaN         NaN        NaN            NaN   
23195610            NaN         NaN        NaN            NaN   
23195611            NaN         NaN        NaN            NaN   
23195612            NaN         NaN        NaN            NaN   
23195613            NaN         NaN        NaN            NaN   
23195614            NaN         NaN        NaN            NaN   
23195615            NaN         NaN        NaN            NaN   

         student_unsure_second  answers_second  fo_rec subdate_rec  \
23195601                   NaN             NaN   124.0  2023-08-19   
23195602                   NaN             NaN    80.0  2023-08-10   
23195603                   NaN             NaN   124.0  2023-08-19   
23195604                   NaN             NaN    80.0  2023-08-10   
23195605                   NaN             NaN   124.0  2023-08-19   
23195606                   NaN             NaN    80.0  2023-08-10   
23195607                   NaN             NaN   124.0  2023-08-19   
23195608                   NaN             NaN    80.0  2023-08-10   
2

In [8]:
len(df_merged)

23195616

In [9]:
# let's save the current dataset for future reference
df_merged.to_csv(f'{path_learnassess_year1}/df_merged.csv',index=False)

#### check rows where answers variables are empty

In [10]:
df_merged[df_merged[['answers_first','answers_second','correct_answers']].isna().all(axis=1)]

spv_first  fo_first    district        sector  school grade  \
22017450        2.0      35.0  'Kicukiro'     'Gikondo'  130313  'P2'   
22017451        0.0      74.0  'Kicukiro'     'Kanombe'  130532  'P3'   
22017452        1.0      21.0  'Kicukiro'    'Kigarama'  130717  'P6'   
22017453        0.0      76.0    'Gasabo'    'Rusororo'  121431  'P5'   
22017454        0.0      95.0  'Kicukiro'  'Nyarugunga'  131007  'P3'   
...             ...       ...         ...           ...     ...   ...   
23195581        NaN       NaN   'Musanze'      'Kinigi'  430704  'P3'   
23195592        NaN       NaN   'Musanze'      'Kinigi'  430704  'P3'   
23195593        NaN       NaN   'Musanze'      'Kinigi'  430704  'P3'   
23195604        NaN       NaN   'Musanze'      'Kinigi'  430704  'P3'   
23195605        NaN       NaN   'Musanze'      'Kinigi'  430704  'P3'   

          student_code subdate_first student_code_unsure         questions  \
22017450  1.303130e-01    2023-08-19            'passed'  p1_leg_cwpm_sub1   
22017451  1.101032e+11    2023-08-01            'passed'  p1_leg_cwpm_sub1   
22017452  1.101042e+11    2023-08-01            'passed'  p1_leg_cwpm_sub1   
22017453  1.102012e+11    2023-08-03            'passed'  p1_leg_cwpm_sub1   
22017454  1.102012e+11    2023-08-02            'passed'  p1_leg_cwpm_sub1   
...                ...           ...                 ...               ...   
23195581  4.307042e+11           NaN                 NaN  p1_leg_cwpm_sub1   
23195592  4.307042e+11           NaN                 NaN  p2_leg_cwpm_sub1   
23195593  4.307042e+11           NaN                 NaN  p2_leg_cwpm_sub1   
23195604  4.307042e+11           NaN                 NaN  p3_leg_cwpm_sub1   
23195605  4.307042e+11           NaN                 NaN  p3_leg_cwpm_sub1   

          answers_first  spv_second  fo_second subdate_second  \
22017450            NaN         NaN        NaN            NaN   
22017451            NaN         5.0       75.0     2023-07-31   
22017452            NaN         3.0        8.0     2023-07-31   
22017453            NaN         3.0      107.0     2023-08-02   
22017454            NaN         5.0       35.0     2023-08-01   
...                 ...         ...        ...            ...   
23195581            NaN         NaN        NaN            NaN   
23195592            NaN         NaN        NaN            NaN   
23195593            NaN         NaN        NaN            NaN   
23195604            NaN         NaN        NaN            NaN   
23195605            NaN         NaN        NaN            NaN   

         student_unsure_second  answers_second  fo_rec subdate_rec  \
22017450                   NaN             NaN     NaN         NaN   
22017451              'passed'             NaN   121.0  2023-08-12   
22017452              'passed'             NaN   126.0  2023-08-11   
22017453              'passed'             NaN    79.0  2023-08-11   
22017454              'passed'             NaN    49.0  2023-08-12   
...                        ...             ...     ...         ...   
23195581                   NaN             NaN   124.0  2023-08-19   
23195592                   NaN             NaN    80.0  2023-08-10   
23195593                   NaN             NaN   124.0  2023-08-19   
23195604                   NaN             NaN    80.0  2023-08-10   
23195605                   NaN             NaN   124.0  2023-08-19   

          correct_answers  
22017450              NaN  
22017451              NaN  
22017452              NaN  
22017453              NaN  
22017454              NaN  
...                   ...  
23195581              NaN  
23195592              NaN  
23195593              NaN  
23195604              NaN  
23195605              NaN  

[165446 rows x 19 columns]

In [23]:
df_merged[(df_merged.answers_first.isna()) & (df_merged.answers_second.isna()) & (df_merged.correct_answers == -1)]

spv_first  fo_first   district    sector  school grade  \
23194800        NaN       NaN  'Musanze'  'Kinigi'  430704  'P3'   
23194801        NaN       NaN  'Musanze'  'Kinigi'  430704  'P3'   
23194802        NaN       NaN  'Musanze'  'Kinigi'  430704  'P3'   
23194803        NaN       NaN  'Musanze'  'Kinigi'  430704  'P3'   
23194804        NaN       NaN  'Musanze'  'Kinigi'  430704  'P3'   
...             ...       ...        ...       ...     ...   ...   
23195611        NaN       NaN  'Musanze'  'Kinigi'  430704  'P3'   
23195612        NaN       NaN  'Musanze'  'Kinigi'  430704  'P3'   
23195613        NaN       NaN  'Musanze'  'Kinigi'  430704  'P3'   
23195614        NaN       NaN  'Musanze'  'Kinigi'  430704  'P3'   
23195615        NaN       NaN  'Musanze'  'Kinigi'  430704  'P3'   

          student_code subdate_first student_code_unsure          questions  \
23194800  4.307042e+11           NaN                 NaN  eng_participation   
23194801  4.307042e+11           NaN                 NaN  eng_participation   
23194802  4.307042e+11           NaN                 NaN    p1_eng_q01_sub1   
23194803  4.307042e+11           NaN                 NaN    p1_eng_q01_sub1   
23194804  4.307042e+11           NaN                 NaN    p1_eng_q01_sub2   
...                ...           ...                 ...                ...   
23195611  4.307042e+11           NaN                 NaN    p3_leg_q03_sub1   
23195612  4.307042e+11           NaN                 NaN    p3_leg_q04_sub1   
23195613  4.307042e+11           NaN                 NaN    p3_leg_q04_sub1   
23195614  4.307042e+11           NaN                 NaN    p3_leg_q05_sub1   
23195615  4.307042e+11           NaN                 NaN    p3_leg_q05_sub1   

          answers_first  spv_second  fo_second subdate_second  \
23194800            NaN         NaN        NaN            NaN   
23194801            NaN         NaN        NaN            NaN   
23194802            NaN         NaN        NaN            NaN   
23194803            NaN         NaN        NaN            NaN   
23194804            NaN         NaN        NaN            NaN   
...                 ...         ...        ...            ...   
23195611            NaN         NaN        NaN            NaN   
23195612            NaN         NaN        NaN            NaN   
23195613            NaN         NaN        NaN            NaN   
23195614            NaN         NaN        NaN            NaN   
23195615            NaN         NaN        NaN            NaN   

         student_unsure_second  answers_second  fo_rec subdate_rec  \
23194800                   NaN             NaN    80.0  2023-08-10   
23194801                   NaN             NaN   124.0  2023-08-19   
23194802                   NaN             NaN    80.0  2023-08-10   
23194803                   NaN             NaN   124.0  2023-08-19   
23194804                   NaN             NaN    80.0  2023-08-10   
...                        ...             ...     ...         ...   
23195611                   NaN             NaN   124.0  2023-08-19   
23195612                   NaN             NaN    80.0  2023-08-10   
23195613                   NaN             NaN   124.0  2023-08-19   
23195614                   NaN             NaN    80.0  2023-08-10   
23195615                   NaN             NaN   124.0  2023-08-19   

          correct_answers  
23194800             -1.0  
23194801             -1.0  
23194802             -1.0  
23194803             -1.0  
23194804             -1.0  
...                   ...  
23195611             -1.0  
23195612             -1.0  
23195613             -1.0  
23195614             -1.0  
23195615             -1.0  

[807 rows x 19 columns]

In [24]:
df_merged[(df_merged['answers_first'].isna()) & (df_merged['answers_second'] == -1 ) & (df_merged['correct_answers'].isna())]

spv_first  fo_first   district       sector  school grade  \
23033641        NaN       NaN  'Gakenke'     'Mataba'  421004  'P4'   
23033802        NaN       NaN  'Gakenke'   'Kivuruga'  420903  'P1'   
23033803        NaN       NaN  'Gakenke'   'Kivuruga'  420903  'P1'   
23033804        NaN       NaN  'Gakenke'   'Kivuruga'  420903  'P1'   
23033805        NaN       NaN  'Gakenke'   'Kivuruga'  420903  'P1'   
...             ...       ...        ...          ...     ...   ...   
23194795        NaN       NaN  'Kayonza'  'Rwinkwavu'  541216  'P4'   
23194796        NaN       NaN  'Kayonza'      'Mwiri'  540712  'P5'   
23194797        NaN       NaN  'Kayonza'      'Mwiri'  540712  'P1'   
23194798        NaN       NaN  'Rutsiro'     'Kivumu'  320401  'P5'   
23194799        NaN       NaN  'Gatsibo'    'Gasange'  530106  'P5'   

          student_code subdate_first student_code_unsure          questions  \
23033641 -5.550000e+02           NaN                 NaN  eng_participation   
23033802  4.209030e+11           NaN                 NaN  eng_participation   
23033803  4.209030e+11           NaN                 NaN  eng_participation   
23033804  4.209030e+11           NaN                 NaN  eng_participation   
23033805  4.209030e+11           NaN                 NaN  eng_participation   
...                ...           ...                 ...                ...   
23194795  5.412162e+11           NaN                 NaN    p3_leg_q05_sub1   
23194796  5.471201e+10           NaN                 NaN    p3_leg_q05_sub1   
23194797  5.471223e+10           NaN                 NaN    p3_leg_q05_sub1   
23194798  5.555550e+05           NaN                 NaN    p3_leg_q05_sub1   
23194799  5.601060e+11           NaN                 NaN    p3_leg_q05_sub1   

          answers_first  spv_second  fo_second subdate_second  \
23033641            NaN         5.0       35.0     2023-07-24   
23033802            NaN         2.0       67.0     2023-07-22   
23033803            NaN         2.0       67.0     2023-07-22   
23033804            NaN         2.0       67.0     2023-07-22   
23033805            NaN         2.0       67.0     2023-07-22   
...                 ...         ...        ...            ...   
23194795            NaN         2.0       65.0     2023-08-03   
23194796            NaN         5.0       70.0     2023-08-07   
23194797            NaN         5.0       70.0     2023-08-07   
23194798            NaN         2.0       34.0     2023-08-08   
23194799            NaN         5.0       49.0     2023-08-23   

         student_unsure_second  answers_second  fo_rec subdate_rec  \
23033641              'passed'            -1.0     NaN         NaN   
23033802              'passed'            -1.0     NaN         NaN   
23033803              'passed'            -1.0     NaN         NaN   
23033804              'passed'            -1.0     NaN         NaN   
23033805              'passed'            -1.0     NaN         NaN   
...                        ...             ...     ...         ...   
23194795              'passed'            -1.0     NaN         NaN   
23194796              'passed'            -1.0     NaN         NaN   
23194797              'passed'            -1.0     NaN         NaN   
23194798              'passed'            -1.0     NaN         NaN   
23194799              'passed'            -1.0     NaN         NaN   

          correct_answers  
23033641              NaN  
23033802              NaN  
23033803              NaN  
23033804              NaN  
23033805              NaN  
...                   ...  
23194795              NaN  
23194796              NaN  
23194797              NaN  
23194798              NaN  
23194799              NaN  

[134839 rows x 19 columns]

In [26]:

df_merged[(df_merged['answers_first'].isna()) & (df_merged['answers_second'] == -1) & (df_merged['correct_answers'] == -1)]


Empty DataFrame
Columns: [spv_first, fo_first, district, sector, school, grade, student_code, subdate_first, student_code_unsure, questions, answers_first, spv_second, fo_second, subdate_second, student_unsure_second, answers_second, fo_rec, subdate_rec, correct_answers]
Index: []

In [27]:

df_merged[(df_merged['answers_first'] == -1) & df_merged['answers_second'].isna() & df_merged['correct_answers'].isna()]


spv_first  fo_first   district       sector  school grade  \
29444           4.0     126.0  'Gakenke'       'Coko'  420211  'P6'   
29936           4.0      91.0  'Gakenke'   'Cyabingo'  420315  'P6'   
29992           4.0      76.0  'Gakenke'   'Cyabingo'  420311  'P1'   
29993           4.0      76.0  'Gakenke'   'Cyabingo'  420311  'P1'   
29994           4.0      76.0  'Gakenke'   'Cyabingo'  420311  'P1'   
...             ...       ...        ...          ...     ...   ...   
23032098        0.0      64.0  'Kayonza'  'Nyamirama'  540919  'P3'   
23033576        4.0     120.0  'Gakenke'   'Cyabingo'  420315  'P6'   
23033601        0.0      30.0  'Gakenke'    'Karambo'  420806  'P1'   
23033602        0.0      22.0  'Gakenke'    'Karambo'  420806  'P2'   
23033603        1.0      71.0  'Gakenke'       'Muzo'  421512  'P2'   

          student_code subdate_first student_code_unsure          questions  \
29444     4.202112e+11    2023-07-24            'passed'  eng_participation   
29936     4.203092e+11    2023-07-22            'passed'  eng_participation   
29992     4.203110e+11    2023-07-22            'passed'  eng_participation   
29993     4.203110e+11    2023-07-22            'passed'  eng_participation   
29994     4.203110e+11    2023-07-22            'passed'  eng_participation   
...                ...           ...                 ...                ...   
23032098  5.409192e+11    2023-08-04            'passed'    p3_leg_q05_sub1   
23033576  5.500000e+01    2023-07-24            'passed'    p3_leg_q05_sub1   
23033601  5.550000e+02    2023-07-22            'passed'    p3_leg_q05_sub1   
23033602  5.555000e+03    2023-07-22            'passed'    p3_leg_q05_sub1   
23033603  5.556000e+03    2023-07-22            'passed'    p3_leg_q05_sub1   

          answers_first  spv_second  fo_second subdate_second  \
29444              -1.0         NaN        NaN            NaN   
29936              -1.0         NaN        NaN            NaN   
29992              -1.0         NaN        NaN            NaN   
29993              -1.0         NaN        NaN            NaN   
29994              -1.0         NaN        NaN            NaN   
...                 ...         ...        ...            ...   
23032098           -1.0         NaN        NaN            NaN   
23033576           -1.0         NaN        NaN            NaN   
23033601           -1.0         NaN        NaN            NaN   
23033602           -1.0         NaN        NaN            NaN   
23033603           -1.0         NaN        NaN            NaN   

         student_unsure_second  answers_second  fo_rec subdate_rec  \
29444                      NaN             NaN     NaN         NaN   
29936                      NaN             NaN     NaN         NaN   
29992                      NaN             NaN     NaN         NaN   
29993                      NaN             NaN     NaN         NaN   
29994                      NaN             NaN     NaN         NaN   
...                        ...             ...     ...         ...   
23032098                   NaN             NaN     NaN         NaN   
23033576                   NaN             NaN     NaN         NaN   
23033601                   NaN             NaN     NaN         NaN   
23033602                   NaN             NaN     NaN         NaN   
23033603                   NaN             NaN     NaN         NaN   

          correct_answers  
29444                 NaN  
29936                 NaN  
29992                 NaN  
29993                 NaN  
29994                 NaN  
...                   ...  
23032098              NaN  
23033576              NaN  
23033601              NaN  
23033602              NaN  
23033603              NaN  

[126739 rows x 19 columns]

In [28]:

df_merged[(df_merged['answers_first'] == -1) & (df_merged['answers_second'].isna()) & (df_merged['correct_answers'] == -1)]


spv_first  fo_first   district     sector  school grade  \
57644           4.0     134.0   'Gasabo'   'Gisozi'  120405  'P2'   
70512           4.0     126.0     'Huye'   'Kinazi'  240501  'P3'   
70684           1.0      51.0     'Huye'   'Kinazi'  240505  'P3'   
74338           0.0     127.0  'Rutsiro'  'Gihango'  320208  'P3'   
74434           4.0      96.0  'Rutsiro'   'Kivumu'  320401  'P6'   
...             ...       ...        ...        ...     ...   ...   
23018671        1.0      51.0  'Musanze'   'Nkotsi'  431104  'P5'   
23019756        1.0      51.0  'Musanze'   'Remera'  431305  'P3'   
23030576        4.0      11.0  'Kayonza'  'Murundi'  540609  'P5'   
23031725        0.0     127.0  'Kayonza'    'Mwiri'  540712  'P4'   
23031815        0.0     137.0  'Kayonza'    'Mwiri'  540712  'P1'   

          student_code subdate_first student_code_unsure        questions  \
57644     1.204050e+11    2023-08-03            'passed'  p1_eng_q01_sub1   
70512     2.405010e+11    2023-08-11            'passed'  p1_eng_q01_sub1   
70684     2.405050e+11    2023-08-10            'passed'  p1_eng_q01_sub1   
74338     3.202082e+11    2023-08-08            'passed'  p1_eng_q01_sub1   
74434     3.204012e+11    2023-08-09            'passed'  p1_eng_q01_sub1   
...                ...           ...                 ...              ...   
23018671  4.311040e+11    2023-08-10            'passed'  p3_leg_q05_sub1   
23019756  4.313050e+11    2023-08-10            'passed'  p3_leg_q05_sub1   
23030576  5.406092e+11    2023-08-04            'passed'  p3_leg_q05_sub1   
23031725  5.407120e+11    2023-08-08            'passed'  p3_leg_q05_sub1   
23031815  5.407122e+11    2023-08-08            'passed'  p3_leg_q05_sub1   

          answers_first  spv_second  fo_second subdate_second  \
57644              -1.0         NaN        NaN            NaN   
70512              -1.0         NaN        NaN            NaN   
70684              -1.0         NaN        NaN            NaN   
74338              -1.0         NaN        NaN            NaN   
74434              -1.0         NaN        NaN            NaN   
...                 ...         ...        ...            ...   
23018671           -1.0         NaN        NaN            NaN   
23019756           -1.0         NaN        NaN            NaN   
23030576           -1.0         NaN        NaN            NaN   
23031725           -1.0         NaN        NaN            NaN   
23031815           -1.0         NaN        NaN            NaN   

         student_unsure_second  answers_second  fo_rec subdate_rec  \
57644                      NaN             NaN    60.0  2023-08-14   
70512                      NaN             NaN   124.0  2023-08-19   
70684                      NaN             NaN    10.0  2023-08-19   
74338                      NaN             NaN   103.0  2023-08-12   
74434                      NaN             NaN    82.0  2023-08-19   
...                        ...             ...     ...         ...   
23018671                   NaN             NaN    14.0  2023-08-23   
23019756                   NaN             NaN    14.0  2023-08-23   
23030576                   NaN             NaN   105.0  2023-08-19   
23031725                   NaN             NaN    46.0  2023-08-19   
23031815                   NaN             NaN    46.0  2023-08-19   

          correct_answers  
57644                -1.0  
70512                -1.0  
70684                -1.0  
74338                -1.0  
74434                -1.0  
...                   ...  
23018671             -1.0  
23019756             -1.0  
23030576             -1.0  
23031725             -1.0  
23031815             -1.0  

[7504 rows x 19 columns]

In [29]:

df_merged[(df_merged['answers_first'] == -1) & (df_merged['answers_second'] == -1) & (df_merged['correct_answers'].isna())]

spv_first  fo_first   district       sector  school grade  \
56595           0.0     100.0   'Gasabo'    'Bumbogo'  120108  'P2'   
56602           0.0     122.0   'Gasabo'    'Bumbogo'  120108  'P2'   
56604           0.0     128.0   'Gasabo'    'Bumbogo'  120108  'P3'   
56605           0.0     128.0   'Gasabo'    'Bumbogo'  120108  'P3'   
56642           0.0     128.0   'Gasabo'    'Bumbogo'  120108  'P3'   
...             ...       ...        ...          ...     ...   ...   
23033556        0.0      55.0  'Kayonza'  'Rwinkwavu'  541217  'P2'   
23033557        0.0      42.0  'Kayonza'  'Rwinkwavu'  541217  'P1'   
23033570        0.0      42.0  'Kayonza'  'Rwinkwavu'  541217  'P1'   
23033574        0.0      42.0  'Kayonza'  'Rwinkwavu'  541217  'P1'   
23033629        0.0      48.0   'Nyanza'     'Busoro'  210210  'P1'   

          student_code subdate_first student_code_unsure        questions  \
56595     1.201082e+11    2023-08-23            'passed'  p1_eng_q01_sub1   
56602     1.201082e+11    2023-08-02            'passed'  p1_eng_q01_sub1   
56604     1.201082e+11    2023-08-02            'passed'  p1_eng_q01_sub1   
56605     1.201082e+11    2023-08-02            'passed'  p1_eng_q01_sub1   
56642     1.201082e+11    2023-08-02            'passed'  p1_eng_q01_sub1   
...                ...           ...                 ...              ...   
23033556  5.412172e+11    2023-08-04            'passed'  p3_leg_q05_sub1   
23033557  5.412172e+11    2023-08-04            'passed'  p3_leg_q05_sub1   
23033570  5.412172e+11    2023-08-04            'passed'  p3_leg_q05_sub1   
23033574  5.412172e+11    2023-08-04            'passed'  p3_leg_q05_sub1   
23033629  5.710052e+11    2023-08-07            'passed'  p3_leg_q05_sub1   

          answers_first  spv_second  fo_second subdate_second  \
56595              -1.0         5.0       73.0     2023-08-01   
56602              -1.0         5.0       73.0     2023-08-01   
56604              -1.0         5.0       94.0     2023-08-01   
56605              -1.0         5.0       94.0     2023-08-01   
56642              -1.0         5.0       94.0     2023-08-01   
...                 ...         ...        ...            ...   
23033556           -1.0         5.0      120.0     2023-08-03   
23033557           -1.0         5.0       70.0     2023-08-03   
23033570           -1.0         5.0       70.0     2023-08-03   
23033574           -1.0         5.0       70.0     2023-08-03   
23033629           -1.0         5.0       38.0     2023-08-04   

         student_unsure_second  answers_second  fo_rec subdate_rec  \
56595                 'passed'            -1.0     NaN         NaN   
56602                 'passed'            -1.0     NaN         NaN   
56604                 'passed'            -1.0     NaN         NaN   
56605                 'passed'            -1.0     NaN         NaN   
56642                 'passed'            -1.0     NaN         NaN   
...                        ...             ...     ...         ...   
23033556              'passed'            -1.0     NaN         NaN   
23033557              'passed'            -1.0     NaN         NaN   
23033570              'passed'            -1.0     NaN         NaN   
23033574              'passed'            -1.0     NaN         NaN   
23033629              'passed'            -1.0     NaN         NaN   

          correct_answers  
56595                 NaN  
56602                 NaN  
56604                 NaN  
56605                 NaN  
56642                 NaN  
...                   ...  
23033556              NaN  
23033557              NaN  
23033570              NaN  
23033574              NaN  
23033629              NaN  

[1346736 rows x 19 columns]

In [31]:
df_merged[(df_merged['answers_first'] == -1) & (df_merged['answers_second'] == -1) & (df_merged['correct_answers'] == -1)]

spv_first  fo_first    district        sector  school grade  \
33542           0.0     137.0   'Gakenke'    'Kivuruga'  420913  'P5'   
56456           0.0      74.0  'Kicukiro'     'Kanombe'  130532  'P3'   
56457           1.0      21.0  'Kicukiro'    'Kigarama'  130717  'P6'   
56458           0.0      76.0    'Gasabo'    'Rusororo'  121431  'P5'   
56459           0.0      95.0  'Kicukiro'  'Nyarugunga'  131007  'P3'   
...             ...       ...         ...           ...     ...   ...   
23033635        1.0     109.0   'Kayonza'   'Rwinkwavu'  541201  'P3'   
23033636        1.0     103.0   'Gatsibo'    'Kiziguro'  530717  'P5'   
23033637        1.0      33.0    'Gasabo'    'Rusororo'  121404  'P3'   
23033638        4.0      26.0      'Huye'    'Gishamvu'  240107  'P6'   
23033639        0.0      95.0    'Nyanza'  'Busasamana'  210120  'P4'   

          student_code subdate_first student_code_unsure          questions  \
33542     4.209132e+11    2023-07-24            'passed'  eng_participation   
56456     1.101032e+11    2023-08-01            'passed'    p1_eng_q01_sub1   
56457     1.101042e+11    2023-08-01            'passed'    p1_eng_q01_sub1   
56458     1.102012e+11    2023-08-03            'passed'    p1_eng_q01_sub1   
56459     1.102012e+11    2023-08-02            'passed'    p1_eng_q01_sub1   
...                ...           ...                 ...                ...   
23033635  5.710452e+11    2023-08-03            'passed'    p3_leg_q05_sub1   
23033636  5.711062e+11    2023-07-25            'passed'    p3_leg_q05_sub1   
23033637  5.712032e+11    2023-08-02            'passed'    p3_leg_q05_sub1   
23033638  5.713062e+11    2023-07-31            'passed'    p3_leg_q05_sub1   
23033639  5.715012e+11    2023-08-07            'passed'    p3_leg_q05_sub1   

          answers_first  spv_second  fo_second subdate_second  \
33542              -1.0         2.0       34.0     2023-07-22   
56456              -1.0         5.0       75.0     2023-07-31   
56457              -1.0         3.0        8.0     2023-07-31   
56458              -1.0         3.0      107.0     2023-08-02   
56459              -1.0         5.0       35.0     2023-08-01   
...                 ...         ...        ...            ...   
23033635           -1.0         3.0       54.0     2023-08-02   
23033636           -1.0         3.0      107.0     2023-07-26   
23033637           -1.0         3.0       19.0     2023-08-03   
23033638           -1.0         2.0      121.0     2023-08-01   
23033639           -1.0         5.0       36.0     2023-08-04   

         student_unsure_second  answers_second  fo_rec subdate_rec  \
33542                 'passed'            -1.0    62.0  2023-08-02   
56456                 'passed'            -1.0   121.0  2023-08-12   
56457                 'passed'            -1.0   126.0  2023-08-11   
56458                 'passed'            -1.0    79.0  2023-08-11   
56459                 'passed'            -1.0    49.0  2023-08-12   
...                        ...             ...     ...         ...   
23033635              'passed'            -1.0   131.0  2023-08-11   
23033636              'passed'            -1.0     4.0  2023-08-08   
23033637              'passed'            -1.0    10.0  2023-08-11   
23033638              'passed'            -1.0    14.0  2023-08-10   
23033639              'passed'            -1.0    19.0  2023-08-12   

          correct_answers  
33542                -1.0  
56456                -1.0  
56457                -1.0  
56458                -1.0  
56459                -1.0  
...                   ...  
23033635             -1.0  
23033636             -1.0  
23033637             -1.0  
23033638             -1.0  
23033639             -1.0  

[17587152 rows x 19 columns]

In [11]:
removable_rows = sum([len(df_merged[df_merged[['answers_first','answers_second','correct_answers']].isna().all(axis=1)]),
     len(df_merged[(df_merged.answers_first.isna()) & (df_merged.answers_second.isna()) & (df_merged.correct_answers == -1)]),
     len(df_merged[(df_merged['answers_first'].isna()) & (df_merged['answers_second'] == -1 ) & (df_merged['correct_answers'].isna())]),
     len(df_merged[(df_merged['answers_first'].isna()) & (df_merged['answers_second'] == -1) & (df_merged['correct_answers'] == -1)]),
     len(df_merged[(df_merged['answers_first'] == -1) & df_merged['answers_second'].isna() & df_merged['correct_answers'].isna()]),
     len(df_merged[(df_merged['answers_first'] == -1) & (df_merged['answers_second'].isna()) & (df_merged['correct_answers'] == -1)]),
     len(df_merged[(df_merged['answers_first'] == -1) & (df_merged['answers_second'] == -1) & (df_merged['correct_answers'].isna())]),
     len(df_merged[(df_merged['answers_first'] == -1) & (df_merged['answers_second'] == -1) & (df_merged['correct_answers'] == -1)])])

In [12]:
print(removable_rows)

19369223


In [13]:
remaining_rows = len(df_merged) - removable_rows
print(remaining_rows)

3826393


We are going to drop <b>19,369,223</b> rows! and only remain with <b>3,826,393 </b> rows!

In [40]:
df_merged.drop(np.r_[df_merged[df_merged[['answers_first','answers_second','correct_answers']].isna().all(axis=1)].index,
                df_merged[(df_merged.answers_first.isna()) & (df_merged.answers_second.isna()) & (df_merged.correct_answers == -1)].index])

spv_first  fo_first    district        sector  school grade  \
0               2.0      35.0  'Kicukiro'     'Gikondo'  130313  'P2'   
1               0.0      74.0  'Kicukiro'     'Kanombe'  130532  'P3'   
2               1.0      21.0  'Kicukiro'    'Kigarama'  130717  'P6'   
3               0.0      76.0    'Gasabo'    'Rusororo'  121431  'P5'   
4               0.0      95.0  'Kicukiro'  'Nyarugunga'  131007  'P3'   
...             ...       ...         ...           ...     ...   ...   
23194798        NaN       NaN   'Rutsiro'      'Kivumu'  320401  'P5'   
23194799        NaN       NaN   'Gatsibo'     'Gasange'  530106  'P5'   
23194905        NaN       NaN   'Musanze'      'Kinigi'  430704  'P3'   
23195228        NaN       NaN   'Musanze'      'Kinigi'  430704  'P3'   
23195230        NaN       NaN   'Musanze'      'Kinigi'  430704  'P3'   

          student_code subdate_first student_code_unsure          questions  \
0         1.303130e-01    2023-08-19            'passed'  eng_participation   
1         1.101032e+11    2023-08-01            'passed'  eng_participation   
2         1.101042e+11    2023-08-01            'passed'  eng_participation   
3         1.102012e+11    2023-08-03            'passed'  eng_participation   
4         1.102012e+11    2023-08-02            'passed'  eng_participation   
...                ...           ...                 ...                ...   
23194798  5.555550e+05           NaN                 NaN    p3_leg_q05_sub1   
23194799  5.601060e+11           NaN                 NaN    p3_leg_q05_sub1   
23194905  4.307042e+11           NaN                 NaN    p3_eng_q02_sub1   
23195228  4.307042e+11           NaN                 NaN    p3_mat_q10_sub1   
23195230  4.307042e+11           NaN                 NaN    p3_mat_q10_sub2   

          answers_first  spv_second  fo_second subdate_second  \
0                   1.0         NaN        NaN            NaN   
1                   1.0         5.0       75.0     2023-07-31   
2                   1.0         3.0        8.0     2023-07-31   
3                   1.0         3.0      107.0     2023-08-02   
4                   1.0         5.0       35.0     2023-08-01   
...                 ...         ...        ...            ...   
23194798            NaN         2.0       34.0     2023-08-08   
23194799            NaN         5.0       49.0     2023-08-23   
23194905            NaN         NaN        NaN            NaN   
23195228            NaN         NaN        NaN            NaN   
23195230            NaN         NaN        NaN            NaN   

         student_unsure_second  answers_second  fo_rec subdate_rec  \
0                          NaN             NaN     NaN         NaN   
1                     'passed'             1.0   121.0  2023-08-12   
2                     'passed'             1.0   126.0  2023-08-11   
3                     'passed'             1.0    79.0  2023-08-11   
4                     'passed'             1.0    49.0  2023-08-12   
...                        ...             ...     ...         ...   
23194798              'passed'            -1.0     NaN         NaN   
23194799              'passed'            -1.0     NaN         NaN   
23194905                   NaN             NaN   124.0  2023-08-19   
23195228                   NaN             NaN    80.0  2023-08-10   
23195230                   NaN             NaN    80.0  2023-08-10   

          correct_answers  
0                     NaN  
1                    -1.0  
2                    -1.0  
3                    -1.0  
4                    -1.0  
...                   ...  
23194798              NaN  
23194799              NaN  
23194905              2.0  
23195228              2.0  
23195230              2.0  

[23029363 rows x 19 columns]

In [14]:
df_merged_sub = df_merged.drop(np.r_[df_merged[df_merged[['answers_first','answers_second','correct_answers']].isna().all(axis=1)].index,
                df_merged[(df_merged.answers_first.isna()) & (df_merged.answers_second.isna()) & (df_merged.correct_answers == -1)].index,
                df_merged[(df_merged['answers_first'].isna()) & (df_merged['answers_second'] == -1 ) & (df_merged['correct_answers'].isna())].index,
                df_merged[(df_merged['answers_first'].isna()) & (df_merged['answers_second'] == -1) & (df_merged['correct_answers'] == -1)].index,
                df_merged[(df_merged['answers_first'] == -1) & df_merged['answers_second'].isna() & df_merged['correct_answers'].isna()].index,
                df_merged[(df_merged['answers_first'] == -1) & (df_merged['answers_second'].isna()) & (df_merged['correct_answers'] == -1)].index,
                df_merged[(df_merged['answers_first'] == -1) & (df_merged['answers_second'] == -1) & (df_merged['correct_answers'].isna())].index,
                df_merged[(df_merged['answers_first'] == -1) & (df_merged['answers_second'] == -1) & (df_merged['correct_answers'] == -1)].index])

print(len(df_merged_sub))

3826393


In [15]:
df_merged_sub.head(15)

spv_first  fo_first    district        sector  school grade  student_code  \
0         2.0      35.0  'Kicukiro'     'Gikondo'  130313  'P2'  1.303130e-01   
1         0.0      74.0  'Kicukiro'     'Kanombe'  130532  'P3'  1.101032e+11   
2         1.0      21.0  'Kicukiro'    'Kigarama'  130717  'P6'  1.101042e+11   
3         0.0      76.0    'Gasabo'    'Rusororo'  121431  'P5'  1.102012e+11   
4         0.0      95.0  'Kicukiro'  'Nyarugunga'  131007  'P3'  1.102012e+11   
5         5.0      77.0   'Gakenke'    'Kivuruga'  420909  'P2'  1.102022e+11   
6         4.0      97.0   'Rutsiro'      'Musasa'  320805  'P6'  1.103142e+11   
7         0.0       4.0  'Kicukiro'     'Gahanga'  130146  'P6'  1.103142e+11   
8         1.0      54.0  'Kicukiro'    'Kigarama'  130717  'P1'  1.103302e+11   
9         4.0     108.0    'Gasabo'      'Gisozi'  120405  'P1'  1.104042e+11   
10        0.0     137.0    'Gasabo'  'Kimihurura'  120805  'P5'  1.104042e+11   
11        4.0     134.0    'Gasabo'       'Nduba'  121201  'P3'  1.104042e+11   
12        0.0     128.0    'Rubavu'     'Gisenyi'  330420  'P3'  1.104052e+11   
13        1.0       6.0  'Kicukiro'      'Niboye'  130905  'P5'  1.104062e+11   
14        0.0      76.0   'Gakenke'        'Coko'  420205  'P5'  1.105042e+11   

   subdate_first student_code_unsure          questions  answers_first  \
0     2023-08-19            'passed'  eng_participation            1.0   
1     2023-08-01            'passed'  eng_participation            1.0   
2     2023-08-01            'passed'  eng_participation            1.0   
3     2023-08-03            'passed'  eng_participation            1.0   
4     2023-08-02            'passed'  eng_participation            1.0   
5     2023-07-24            'passed'  eng_participation            1.0   
6     2023-08-09            'passed'  eng_participation            1.0   
7     2023-08-01            'passed'  eng_participation            1.0   
8     2023-08-01            'passed'  eng_participation            1.0   
9     2023-08-03            'passed'  eng_participation            0.0   
10    2023-08-02            'passed'  eng_participation            1.0   
11    2023-08-04            'passed'  eng_participation            1.0   
12    2023-07-28            'passed'  eng_participation            1.0   
13    2023-08-01            'passed'  eng_participation            1.0   
14    2023-08-14            'passed'  eng_participation            1.0   

    spv_second  fo_second subdate_second student_unsure_second  \
0          NaN        NaN            NaN                   NaN   
1          5.0       75.0     2023-07-31              'passed'   
2          3.0        8.0     2023-07-31              'passed'   
3          3.0      107.0     2023-08-02              'passed'   
4          5.0       35.0     2023-08-01              'passed'   
5          5.0       16.0     2023-07-24              'passed'   
6          2.0       22.0     2023-08-08              'passed'   
7          5.0       13.0     2023-07-31              'passed'   
8          3.0       26.0     2023-07-31              'passed'   
9          2.0       20.0     2023-08-02              'passed'   
10         5.0       80.0     2023-08-03              'passed'   
11         2.0       67.0     2023-08-02              'passed'   
12         5.0       36.0     2023-07-27              'passed'   
13         3.0      106.0     2023-07-31              'passed'   
14         5.0       73.0     2023-08-14              'passed'   

    answers_second  fo_rec subdate_rec  correct_answers  
0              NaN     NaN         NaN              NaN  
1              1.0   121.0  2023-08-12             -1.0  
2              1.0   126.0  2023-08-11             -1.0  
3              1.0    79.0  2023-08-11             -1.0  
4              1.0    49.0  2023-08-12             -1.0  
5             -1.0    57.0  2023-08-02              1.0  
6              1.0   133.0  2023-08-12             -1.0  
7

In [16]:
# let's save the current dataset for future reference
df_merged_sub.to_csv(f'{path_learnassess_year1}/df_merged_sub.csv',index=False)

In [6]:
# import Data 
df_merged_sub = pd.read_csv(f'{path_learnassess_year1}/df_merged_sub.csv')

In [7]:
# creating a column that check whether the first team answers are correct

df_merged_sub['first_correct'] = np.where((df_merged_sub['correct_answers'].notna()) & (df_merged_sub['correct_answers'] != -1) & (df_merged_sub['answers_first'] == df_merged_sub['correct_answers']),
                                          "correct","")
df_merged_sub['first_correct'].value_counts()

           3649909
correct     176484
Name: first_correct, dtype: int64

In [8]:
df_merged_sub['first_correct'] = np.where((df_merged_sub['answers_first'].notna()) & (df_merged_sub['answers_second'].notna()) & (df_merged_sub['answers_first'] != -1) & (df_merged_sub['answers_second'] != -1) & (df_merged_sub['answers_first'] == df_merged_sub['answers_second']) & ((df_merged_sub['correct_answers'].isna()) | (df_merged_sub['correct_answers'] == -1)),
                                          "correct",df_merged_sub['first_correct'])
df_merged_sub['first_correct'].value_counts()

correct    3608479
            217914
Name: first_correct, dtype: int64

In [19]:
df_merged_sub.head(12)

spv_first  fo_first    district        sector  school grade  student_code  \
0         2.0      35.0  'Kicukiro'     'Gikondo'  130313  'P2'  1.303130e-01   
1         0.0      74.0  'Kicukiro'     'Kanombe'  130532  'P3'  1.101032e+11   
2         1.0      21.0  'Kicukiro'    'Kigarama'  130717  'P6'  1.101042e+11   
3         0.0      76.0    'Gasabo'    'Rusororo'  121431  'P5'  1.102012e+11   
4         0.0      95.0  'Kicukiro'  'Nyarugunga'  131007  'P3'  1.102012e+11   
5         5.0      77.0   'Gakenke'    'Kivuruga'  420909  'P2'  1.102022e+11   
6         4.0      97.0   'Rutsiro'      'Musasa'  320805  'P6'  1.103142e+11   
7         0.0       4.0  'Kicukiro'     'Gahanga'  130146  'P6'  1.103142e+11   
8         1.0      54.0  'Kicukiro'    'Kigarama'  130717  'P1'  1.103302e+11   
9         4.0     108.0    'Gasabo'      'Gisozi'  120405  'P1'  1.104042e+11   
10        0.0     137.0    'Gasabo'  'Kimihurura'  120805  'P5'  1.104042e+11   
11        4.0     134.0    'Gasabo'       'Nduba'  121201  'P3'  1.104042e+11   

   subdate_first student_code_unsure          questions  answers_first  \
0     2023-08-19            'passed'  eng_participation            1.0   
1     2023-08-01            'passed'  eng_participation            1.0   
2     2023-08-01            'passed'  eng_participation            1.0   
3     2023-08-03            'passed'  eng_participation            1.0   
4     2023-08-02            'passed'  eng_participation            1.0   
5     2023-07-24            'passed'  eng_participation            1.0   
6     2023-08-09            'passed'  eng_participation            1.0   
7     2023-08-01            'passed'  eng_participation            1.0   
8     2023-08-01            'passed'  eng_participation            1.0   
9     2023-08-03            'passed'  eng_participation            0.0   
10    2023-08-02            'passed'  eng_participation            1.0   
11    2023-08-04            'passed'  eng_participation            1.0   

    spv_second  fo_second subdate_second student_unsure_second  \
0          NaN        NaN            NaN                   NaN   
1          5.0       75.0     2023-07-31              'passed'   
2          3.0        8.0     2023-07-31              'passed'   
3          3.0      107.0     2023-08-02              'passed'   
4          5.0       35.0     2023-08-01              'passed'   
5          5.0       16.0     2023-07-24              'passed'   
6          2.0       22.0     2023-08-08              'passed'   
7          5.0       13.0     2023-07-31              'passed'   
8          3.0       26.0     2023-07-31              'passed'   
9          2.0       20.0     2023-08-02              'passed'   
10         5.0       80.0     2023-08-03              'passed'   
11         2.0       67.0     2023-08-02              'passed'   

    answers_second  fo_rec subdate_rec  correct_answers first_correct  
0              NaN     NaN         NaN              NaN                
1              1.0   121.0  2023-08-12             -1.0       correct  
2              1.0   126.0  2023-08-11             -1.0       correct  
3              1.0    79.0  2023-08-11             -1.0       correct  
4              1.0    49.0  2023-08-12             -1.0       correct  
5             -1.0    57.0  2023-08-02              1.0       correct  
6              1.0   133.0  2023-08-12             -1.0       correct  
7              1.0   128.0  2023-08-11             -1.0       correct  
8              1.0    36.0  2023-08-11             -1.0       correct  
9              0.0    22.0  2023-08-11             -1.0       correct  
10             1.0    39.0  2023-08-11             -1.0       correct  
11             1.0   106.0  2023-08-11             -1.0       correct

In [20]:
df_merged_sub['correct_answers'].value_counts()

-1.0     3240065
 1.0      177431
 2.0      108175
 0.0       50711
 27.0         39
          ...   
 52.0          2
 51.0          2
 55.0          1
 53.0          1
 57.0          1
Name: correct_answers, Length: 61, dtype: int64

In [21]:
df_merged_sub[(df_merged_sub['answers_first'] == df_merged_sub['correct_answers'])]['correct_answers'].value_counts()

 1.0     94659
 2.0     55853
 0.0     25771
-1.0      5184
 27.0       19
 41.0       12
 26.0        9
 59.0        9
 29.0        7
 35.0        7
 40.0        7
 23.0        7
 30.0        7
 37.0        7
 17.0        7
 19.0        5
 45.0        5
 10.0        4
 48.0        4
 3.0         4
 21.0        4
 18.0        4
 16.0        4
 22.0        4
 34.0        4
 6.0         4
 39.0        3
 20.0        3
 15.0        3
 13.0        3
 42.0        3
 25.0        3
 14.0        3
 38.0        3
 11.0        3
 54.0        3
 32.0        2
 28.0        2
 8.0         2
 56.0        2
 46.0        2
 9.0         2
 24.0        2
 5.0         1
 53.0        1
 7.0         1
 49.0        1
 33.0        1
 31.0        1
 43.0        1
 51.0        1
 4.0         1
 44.0        1
 52.0        1
 36.0        1
 58.0        1
Name: correct_answers, dtype: int64

In [22]:
df_merged_sub[(df_merged_sub['answers_second'] == df_merged_sub['correct_answers'])]['correct_answers'].value_counts()

 1.0     80989
 2.0     50522
 0.0     21792
-1.0       867
 41.0       20
 27.0       17
 59.0       12
 25.0       11
 20.0       11
 10.0       10
 30.0        9
 21.0        8
 24.0        8
 16.0        8
 23.0        8
 28.0        7
 32.0        7
 31.0        6
 36.0        6
 35.0        6
 39.0        6
 40.0        6
 29.0        6
 22.0        6
 6.0         5
 26.0        5
 34.0        5
 11.0        5
 15.0        5
 38.0        5
 4.0         5
 18.0        4
 37.0        4
 33.0        4
 5.0         4
 7.0         4
 3.0         3
 19.0        3
 9.0         3
 47.0        3
 13.0        3
 48.0        3
 50.0        3
 14.0        3
 42.0        3
 43.0        3
 49.0        2
 56.0        2
 12.0        2
 17.0        2
 44.0        2
 45.0        1
 55.0        1
 8.0         1
 51.0        1
 58.0        1
Name: correct_answers, dtype: int64

In [ ]:
df_merged_sub[(df_merged_sub['answers_first'] == df_merged_sub['correct_answers'])]['correct_answers'].value_counts()

In [31]:
# checking rows where both teams and reconciliation have the same value
comp_cols = ['answers_first','answers_second', 'correct_answers']
df_merged_sub[df_merged_sub[comp_cols].eq(df_merged_sub[comp_cols[0]],axis = 0).all(axis = 1)]['first_correct'].value_counts()

correct    1698
Name: first_correct, dtype: int64

In [ ]:
df_merged_sub[df_merged_sub[comp_cols].eq(df_merged_sub[comp_cols[0]],axis = 0).all(axis = 1)]

In [9]:
# creating a column that check whether the second team answers are correct

df_merged_sub['second_correct'] = np.where((df_merged_sub['correct_answers'].notna()) & (df_merged_sub['correct_answers'] != -1) & (df_merged_sub['answers_second'] == df_merged_sub['correct_answers']),
                                          "correct",
                                          np.where((df_merged_sub['answers_second'].notna()) & (df_merged_sub['answers_first'].notna()) & (df_merged_sub['answers_second'] != -1) & (df_merged_sub['answers_first'] != -1) & (df_merged_sub['answers_first'] == df_merged_sub['answers_second']) & ((df_merged_sub['correct_answers'].isna()) | (df_merged_sub['correct_answers'] == -1)),
                                          "correct",""))
df_merged_sub['second_correct'].value_counts()

correct    3585576
            240817
Name: second_correct, dtype: int64

In [10]:
# let's save the current dataset for future reference
df_merged_sub.to_csv(f'{path_learnassess_year1}/df_merged_sub_31jan.csv',index=False)

we are going to create variables expressing courses

In [8]:
# import Data 
df_merged_sub = pd.read_csv(f'{path_learnassess_year1}/df_merged_sub_31jan.csv')

In [10]:
print(df_merged_sub['first_correct'].value_counts(dropna=False))
print(df_merged_sub['second_correct'].value_counts(dropna=False))

correct    3608479
NaN         217914
Name: first_correct, dtype: int64
correct    3585576
NaN         240817
Name: second_correct, dtype: int64


In [11]:
df_merged_sub.head(3)

spv_first  fo_first    district      sector  school grade  student_code  \
0        2.0      35.0  'Kicukiro'   'Gikondo'  130313  'P2'  1.303130e-01   
1        0.0      74.0  'Kicukiro'   'Kanombe'  130532  'P3'  1.101032e+11   
2        1.0      21.0  'Kicukiro'  'Kigarama'  130717  'P6'  1.101042e+11   

  subdate_first student_code_unsure          questions  ...  spv_second  \
0    2023-08-19            'passed'  eng_participation  ...         NaN   
1    2023-08-01            'passed'  eng_participation  ...         5.0   
2    2023-08-01            'passed'  eng_participation  ...         3.0   

   fo_second  subdate_second student_unsure_second answers_second  fo_rec  \
0        NaN             NaN                   NaN            NaN     NaN   
1       75.0      2023-07-31              'passed'            1.0   121.0   
2        8.0      2023-07-31              'passed'            1.0   126.0   

   subdate_rec correct_answers  first_correct second_correct  
0          NaN             NaN            NaN            NaN  
1   2023-08-12            -1.0        correct        correct  
2   2023-08-11            -1.0        correct        correct  

[3 rows x 21 columns]

In [12]:
# first let's add the "incorrect" value to first_correct and second_correct
df_merged_sub['first_correct'] = np.where(df_merged_sub['first_correct'].isna(), "incorrect", df_merged_sub['first_correct'])
df_merged_sub['second_correct'] = np.where(df_merged_sub['second_correct'].isna(), "incorrect", df_merged_sub['second_correct'])
print(df_merged_sub['first_correct'].value_counts())
print(df_merged_sub['second_correct'].value_counts())

correct      3608479
incorrect     217914
Name: first_correct, dtype: int64
correct      3585576
incorrect     240817
Name: second_correct, dtype: int64


from the above, the second team had more incorrect answers than the first team.

In [13]:
df_merged_sub[(df_merged_sub['answers_first'].notna()) & (df_merged_sub['answers_first'] != -1) & 
              ((df_merged_sub['answers_second'].isna() & df_merged_sub['correct_answers'].isna()) | 
               (df_merged_sub['answers_second'].isna() & df_merged_sub['correct_answers'] == -1) |
               ((df_merged_sub['answers_second'] == -1) & df_merged_sub['correct_answers'].isna()) |
               ((df_merged_sub['answers_second'] == -1) & df_merged_sub['correct_answers'] == -1))][['district', 'sector', 'school', 'grade', 'student_code', 'questions', 'answers_first', 'answers_second', 'correct_answers', 'first_correct', 'second_correct']]

district      sector  school grade  student_code  \
0        'Kicukiro'   'Gikondo'  130313  'P2'  1.303130e-01   
97         'Gasabo'   'Bumbogo'  120108  'P2'  1.201082e+11   
881        'Gasabo'  'Gikomero'  120308  'P3'  1.203082e+11   
1247       'Gasabo'    'Gisozi'  120405  'P4'  1.204052e+11   
1324       'Gasabo'    'Gisozi'  120405  'P6'  1.204052e+11   
...             ...         ...     ...   ...           ...   
3800512   'Gakenke'  'Kivuruga'  420902  'P3'  4.209022e+11   
3800513   'Gakenke'  'Kivuruga'  420902  'P3'  4.209022e+11   
3800515   'Gakenke'  'Kivuruga'  420902  'P3'  4.209022e+11   
3800516   'Gakenke'  'Kivuruga'  420902  'P3'  4.209022e+11   
3800620   'Gakenke'      'Muzo'  421509  'P3'  4.215092e+11   

                 questions  answers_first  answers_second  correct_answers  \
0        eng_participation            1.0             NaN              NaN   
97       eng_participation            1.0             NaN              NaN   
881      eng_participation            1.0             NaN              NaN   
1247     eng_participation            0.0             NaN              NaN   
1324     eng_participation            1.0             NaN              NaN   
...                    ...            ...             ...              ...   
3800512    p3_leg_q05_sub1            2.0             NaN              NaN   
3800513    p3_leg_q05_sub1            2.0             NaN              NaN   
3800515    p3_leg_q05_sub1            2.0             NaN              NaN   
3800516    p3_leg_q05_sub1            2.0             NaN              NaN   
3800620    p3_leg_q05_sub1            2.0             NaN              NaN   

        first_correct second_correct  
0           incorrect      incorrect  
97          incorrect      incorrect  
881         incorrect      incorrect  
1247        incorrect      incorrect  
1324        incorrect      incorrect  
...               ...            ...  
3800512     incorrect      incorrect  
3800513     incorrect      incorrect  
3800515     incorrect      incorrect  
3800516     incorrect      incorrect  
3800620     incorrect      incorrect  

[22774 rows x 11 columns]

In [14]:
df_merged_sub[(df_merged_sub['answers_second'].notna()) & (df_merged_sub['answers_second'] != -1) & 
              ((df_merged_sub['answers_first'].isna() & df_merged_sub['correct_answers'].isna()) | 
               (df_merged_sub['answers_first'].isna() & df_merged_sub['correct_answers'] == -1) |
               ((df_merged_sub['answers_first'] == -1) & df_merged_sub['correct_answers'].isna()) |
               ((df_merged_sub['answers_first'] == -1) & df_merged_sub['correct_answers'] == -1))][['district', 'sector', 'school', 'grade', 'student_code', 'questions', 'answers_first', 'answers_second', 'correct_answers', 'first_correct', 'second_correct']]

district        sector  school grade  student_code  \
3459113  'Gatsibo'  'Nyagihanga'  531103  'P6'  5.311032e+11   
3468494  'Gatsibo'  'Nyagihanga'  531103  'P6'  5.311032e+11   
3477875  'Gatsibo'  'Nyagihanga'  531103  'P6'  5.311032e+11   
3487256  'Gatsibo'  'Nyagihanga'  531103  'P6'  5.311032e+11   
3496637  'Gatsibo'  'Nyagihanga'  531103  'P6'  5.311032e+11   
...            ...           ...     ...   ...           ...   
3826385  'Gatsibo'     'Ngarama'  531010  'P3'  5.310102e+11   
3826386   'Gasabo'     'Rutunga'  121502  'P3'  1.215022e+11   
3826387   'Rubavu'   'Nyakiriba'  330808  'P3'  3.308082e+11   
3826388  'Musanze'     'Musanze'  431009  'P3'  4.310092e+11   
3826389  'Gatsibo'     'Ngarama'  531010  'P3'  5.310102e+11   

                 questions  answers_first  answers_second  correct_answers  \
3459113    p6_kin_q01_sub1           -1.0             2.0              NaN   
3468494    p6_kin_q01_sub2           -1.0             2.0              NaN   
3477875  p6_kin_q02_sub1_1           -1.0             2.0              NaN   
3487256  p6_kin_q02_sub1_2           -1.0             2.0              NaN   
3496637  p6_kin_q03_sub1_1           -1.0             2.0              NaN   
...                    ...            ...             ...              ...   
3826385    p3_leg_q04_sub1            NaN             2.0              NaN   
3826386    p3_leg_q05_sub1            NaN             1.0              NaN   
3826387    p3_leg_q05_sub1            NaN             2.0              NaN   
3826388    p3_leg_q05_sub1            NaN             2.0              NaN   
3826389    p3_leg_q05_sub1            NaN             2.0              NaN   

        first_correct second_correct  
3459113     incorrect      incorrect  
3468494     incorrect      incorrect  
3477875     incorrect      incorrect  
3487256     incorrect      incorrect  
3496637     incorrect      incorrect  
...               ...            ...  
3826385     incorrect      incorrect  
3826386     incorrect      incorrect  
3826387     incorrect      incorrect  
3826388     incorrect      incorrect  
3826389     incorrect      incorrect  

[25212 rows x 11 columns]

As we can see there are entries where only one team managed to enter for that specific subquestion we can ignore those entries as they are not consequential to our analysis.

In [15]:
expected = len(df_merged_sub) - 25212 - 22774
print(expected)

3778407


In [16]:
df_merged_reduced = df_merged_sub.drop(np.r_[df_merged_sub[(df_merged_sub['answers_first'].notna()) & (df_merged_sub['answers_first'] != -1) & 
              ((df_merged_sub['answers_second'].isna() & df_merged_sub['correct_answers'].isna()) | 
               (df_merged_sub['answers_second'].isna() & df_merged_sub['correct_answers'] == -1) |
               ((df_merged_sub['answers_second'] == -1) & df_merged_sub['correct_answers'].isna()) |
               ((df_merged_sub['answers_second'] == -1) & df_merged_sub['correct_answers'] == -1))][['district', 'sector', 'school', 'grade', 'student_code', 'questions', 'answers_first', 'answers_second', 'correct_answers', 'first_correct', 'second_correct']].index,
               df_merged_sub[(df_merged_sub['answers_second'].notna()) & (df_merged_sub['answers_second'] != -1) & 
              ((df_merged_sub['answers_first'].isna() & df_merged_sub['correct_answers'].isna()) | 
               (df_merged_sub['answers_first'].isna() & df_merged_sub['correct_answers'] == -1) |
               ((df_merged_sub['answers_first'] == -1) & df_merged_sub['correct_answers'].isna()) |
               ((df_merged_sub['answers_first'] == -1) & df_merged_sub['correct_answers'] == -1))][['district', 'sector', 'school', 'grade', 'student_code', 'questions', 'answers_first', 'answers_second', 'correct_answers', 'first_correct', 'second_correct']].index],
               axis = 0)
print(len(df_merged_reduced))

3778407


In [17]:
df_merged_reduced.head(12)

spv_first  fo_first    district        sector  school grade  student_code  \
1         0.0      74.0  'Kicukiro'     'Kanombe'  130532  'P3'  1.101032e+11   
2         1.0      21.0  'Kicukiro'    'Kigarama'  130717  'P6'  1.101042e+11   
3         0.0      76.0    'Gasabo'    'Rusororo'  121431  'P5'  1.102012e+11   
4         0.0      95.0  'Kicukiro'  'Nyarugunga'  131007  'P3'  1.102012e+11   
5         5.0      77.0   'Gakenke'    'Kivuruga'  420909  'P2'  1.102022e+11   
6         4.0      97.0   'Rutsiro'      'Musasa'  320805  'P6'  1.103142e+11   
7         0.0       4.0  'Kicukiro'     'Gahanga'  130146  'P6'  1.103142e+11   
8         1.0      54.0  'Kicukiro'    'Kigarama'  130717  'P1'  1.103302e+11   
9         4.0     108.0    'Gasabo'      'Gisozi'  120405  'P1'  1.104042e+11   
10        0.0     137.0    'Gasabo'  'Kimihurura'  120805  'P5'  1.104042e+11   
11        4.0     134.0    'Gasabo'       'Nduba'  121201  'P3'  1.104042e+11   
12        0.0     128.0    'Rubavu'     'Gisenyi'  330420  'P3'  1.104052e+11   

   subdate_first student_code_unsure          questions  ...  spv_second  \
1     2023-08-01            'passed'  eng_participation  ...         5.0   
2     2023-08-01            'passed'  eng_participation  ...         3.0   
3     2023-08-03            'passed'  eng_participation  ...         3.0   
4     2023-08-02            'passed'  eng_participation  ...         5.0   
5     2023-07-24            'passed'  eng_participation  ...         5.0   
6     2023-08-09            'passed'  eng_participation  ...         2.0   
7     2023-08-01            'passed'  eng_participation  ...         5.0   
8     2023-08-01            'passed'  eng_participation  ...         3.0   
9     2023-08-03            'passed'  eng_participation  ...         2.0   
10    2023-08-02            'passed'  eng_participation  ...         5.0   
11    2023-08-04            'passed'  eng_participation  ...         2.0   
12    2023-07-28            'passed'  eng_participation  ...         5.0   

    fo_second  subdate_second student_unsure_second answers_second  fo_rec  \
1        75.0      2023-07-31              'passed'            1.0   121.0   
2         8.0      2023-07-31              'passed'            1.0   126.0   
3       107.0      2023-08-02              'passed'            1.0    79.0   
4        35.0      2023-08-01              'passed'            1.0    49.0   
5        16.0      2023-07-24              'passed'           -1.0    57.0   
6        22.0      2023-08-08              'passed'            1.0   133.0   
7        13.0      2023-07-31              'passed'            1.0   128.0   
8        26.0      2023-07-31              'passed'            1.0    36.0   
9        20.0      2023-08-02              'passed'            0.0    22.0   
10       80.0      2023-08-03              'passed'            1.0    39.0   
11       67.0      2023-08-02              'passed'            1.0   106.0   
12       36.0      2023-07-27              'passed'            1.0    89.0   

    subdate_rec correct_answers  first_correct second_correct  
1    2023-08-12            -1.0        correct        correct  
2    2023-08-11            -1.0        correct        correct  
3    2023-08-11            -1.0        correct        correct  
4    2023-08-12            -1.0        correct        correct  
5    2023-08-02             1.0        correct      incorrect  
6    2023-08-12            -1.0        correct        correct  
7    2023-08-11            -1.0        correct        correct  
8    2023-08-11            -1.0        correct        correct  
9    2023-08-11            -1.0        correct        correct  
10   2023-08-11            -1.0        correct        correct  
11   2023-08-11            -1.0        correct        correct  
12   2023-08-10            -1.0        correct        correct  

[12 rows x 21 columns]

In [20]:
# creating a variable that identifies the course 
# we start by differentiating questions that check participation and real questions
df_merged_reduced["participation"] = np.where(df_merged_reduced["questions"].str.endswith("participation"),'yes','no')
print(df_merged_reduced["participation"].value_counts(dropna=False))

no     3610155
yes     168252
Name: participation, dtype: int64


In [ ]:
pd.DataFrame(df_merged_reduced[df_merged_reduced["participation"] == 'no']['questions'].value_counts()).head(120)

In [56]:
df_merged_reduced['questions'].str.split("_").str[2:].str.join('_')

1                  
2                  
3                  
4                  
5                  
             ...   
3801227    q05_sub1
3801228    q05_sub1
3826390    q02_sub1
3826391    q10_sub1
3826392    q10_sub2
Name: questions, Length: 3778407, dtype: object

In [35]:
df_merged_reduced['questions'][3101227].split("_")[1]

'kin'

In [45]:
df_merged_reduced['course'] = np.where(df_merged_reduced["participation"] == 'no', df_merged_reduced['questions'].str.split("_").str[1],df_merged_reduced['questions'].str.split("_").str[0])
print(df_merged_reduced['course'].value_counts(dropna=False))

eng      1471135
mat      1451220
kin       769697
leg        30271
legra      28525
kiny       27559
Name: course, dtype: int64


In [57]:
df_merged_reduced['question_number'] = np.where(df_merged_reduced["participation"] == 'no', df_merged_reduced['questions'].str.split("_").str[2],'invalid')
print(df_merged_reduced['question_number'].value_counts(dropna=False))

q05        432357
q01        393842
q06        380945
q04        366832
q02        331877
q03        319448
q08        314841
q07        259956
q10        225115
q09        195917
invalid    168252
q11        147704
q12        110474
q13         54156
q14         35816
q15         26889
q16          8981
cwpm         5005
Name: question_number, dtype: int64


In [58]:
df_merged_reduced['subquestion'] = np.where(df_merged_reduced["participation"] == 'no', df_merged_reduced['questions'].str.split("_").str[2:].str.join('_'),'invalid')
print(df_merged_reduced['subquestion'].value_counts(dropna=False))

invalid       168252
q05_sub1      144327
q04_sub1      144327
q07_sub1      139274
q08_sub1      139274
q02_sub1      125627
q06_sub1      120992
q04_sub2      120741
q01_sub2      120737
q01_sub1      117271
q10_sub1      111443
q05_sub2      111152
q03_sub1      107529
q09_sub1      102272
q08_sub2       92888
q11_sub1       92680
q07_sub2       92665
q02_sub2       84017
q06_sub2       83907
q05_sub3       73916
q04_sub3       64807
q12_sub1       64380
q02_sub3       56589
q06_sub3       56290
q01_sub3       55534
q03_sub2       46409
q08_sub3       46405
q12_sub2       46094
q10_sub2       37820
q09_sub2       37819
q05_sub4       37365
q03_sub1_2     36798
q03_sub1_1     36798
q05_sub5       28213
q01_sub4       28056
q07_sub3       28017
q06_sub4       27925
q04_sub4       27805
q03_sub3       27629
q11_sub2       27428
q01_sub1_2     27057
q01_sub1_1     27057
q10_sub3       19216
q10_sub4       19216
q02_sub1_2     18701
q02_sub1_1     18701
q09_sub1_2     18525
q09_sub1_1   